### ISSUE TITLE
Menu - Mudar ícone do blog

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#1]
Pode me mostrar/enviar o ícone?

**Comment by amedtler** [comment]
Sabe me dizer qual será o ícone?

**Comment by arielrinnert** [comment]
Andreson essa arte eu não tenho pronta. É pra trocar o ícone que está lá (parece um balão de fala) por esta  revista (http://virtualpress.com.br/wp-content/uploads/2015/02/icone_revista.png).

Como você precisa do formato do arquivo? Ai eu peço pra mar criar ele.. na real e só ajustar o tamanho e a cor né?

**Comment by amedtler** [comment]
Alterado

**Comment by amedtler** [comment]
Ficou ok?

**Comment by arielrinnert** [comment]
Perfeito!
