### ISSUE TITLE
Checkout - Ajustar calculo frete

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#10]

**Comment by amedtler** [comment]
Isso era referente ao código de contrato com os correios, correto? Já tem esse código?

**Comment by arielrinnert** [comment]
tenho, vou verificar no escritório amanhã

**Comment by amedtler** [comment]
Da uma olhada na documentação que recebeu do correio para essa integração e me encaminha.

**Comment by arielrinnert** [comment]
Vou te passar os dados do correio que encontrei aqui junto do contato da pessoa lá do correio que resolve isso ok?

Número do contrato: 9912393595
Código ADM: 16079604
SERVIÇOS CONTRATADOS:

SEDEX 40096
PAC 41068
Contato: tatianebrasil@correios.com.br

**Comment by arielrinnert** [comment]
fica associada a integração do woocommerce
