### ISSUE TITLE
Produtos fora de estoque

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#102]
Quando o produto está fora de estoque e o cliente tentar adicionar ao carrinho, aparecer aviso que não está disponível e jogar o usuário para a faixa “Nossos outros produtos” (ao invés de jogá-lo pra Home Page)

**Comment by amedtler** [comment]
Fiz um pouco diferente, na real fiz como é padrão na maioria dos sites. Quando está fora de estoque, tirei o botão adicionar ao carrinho. Ou seja, se está fora do estoque, não adiciona ao carrinho, de forma alguma.

**Comment by arielrinnert** [comment]
melhor assim!fechou
