### ISSUE TITLE
Ajustar condições específicas dos acessórios (porta capsulas - case)

### ISSUE THREAD

**Issue by arielrinnert** [amedtler/oceandrop#104]
Fala Andreson! Conseguimos fazer essas condições especiais para as páginas dos porta capsulas?

Home:
- retirar valor por dia (essa é pros acessórios em geral..)

Produtos: 
- ajustar posição das estrelas da foto quadrada e das mídias sociais
- retirar selos de certificação
- (manter espaço "grandinho" entre a foto quadrada e o primeiro banner)
- desativar faixa de benefícios e botões de compartilhamento incorporados..
- desativar faixa de depoimentos
- desativar faixa de apoio ao consumo
- desativar faixa contra indicações
- desativar faixa do blog

**Comment by amedtler** [comment]
Ta feito. 
Na página da edição do produto vai continuar aparecendo as informações de valor por dia, assim como outras informações (não consigo remover especificamente por essa categoria), mas não vai aparecer no site.  
O problema de estar quebrando a foto é que ela não está com o tamanho 414x414px. É só ajustar que vai ficar certo. (fiz um esquema aqui que nas próximas já vai ajustar automático, só ajusta para essas duas fotos, pois a foto já está no servidor.)

Publica um desses produtos e veja se ficou tudo ok.

**Comment by arielrinnert** [comment]
Fala Andreson!

Ficou top! Arrumei as fotos lá... só duas coisas: 
1) manter o mesmo espaçamento antes da foto quadrada depois da foto...
2) barra fixa de compra deve aparecer até a foto quadrada, no banner ela já deve sumir..

**Comment by amedtler** [comment]
Ajustado. 
Talvez tenha que atualizar a página quando for testar. 
O cache demora um tempo até limpar automaticamente.

**Comment by arielrinnert** [comment]
Ta da hora isso ai!

**Comment by arielrinnert** [comment]
Só vi uma coisa na real, não ta aparecendo o porta capsulas como opção de outros produtos naquela faixa embaixo..

**Comment by arielrinnert** [comment]
feito!
