### ISSUE TITLE
Geral -Padronizar fontes

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#105]
Padronizar fontes (manter, para todas as faixas, padrão de fontes [inclusive formato de maiúsculo e minísculo], tamanhos e espaçamentos de títulos, subtítulos e textos, da faixa benefício da Home Page)

Qual é o padrão? 
Devo me basear por qual?

**Comment by arielrinnert** [comment]
Então, você pode padronizar conforme a faixa de benefícios na home, tipo assim:
![image](https://cloud.githubusercontent.com/assets/19783148/18458867/4f4c5acc-793b-11e6-8af6-8e8c0f0203f4.png)

Título, subtítulo e textos..

**Comment by arielrinnert** [comment]
feito esse?

**Comment by arielrinnert** [comment]
@amedtler previsão pra esse? @roelsmich coloca a @margpm pra revisar esse tbm?

**Comment by amedtler** [comment]
Estou fazendo as atividades conforme a prioridade que estão me passando, essa atividade ainda não fiz.

**Comment by amedtler** [comment]
Fiz alguns ajustes, acredito que está ok. Se tiver algo que precise ser corrigido é só avisar.

**Comment by roelsmich** [comment]
beleza, vou encerrar. Quando tiver algo eu abro de novo
