### ISSUE TITLE
Geral - Padronizar cores

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#106]
Padronizar cores (a cor base de todos botões é a mesma do batão “Carrinho”, com exceção do botão no rodapé, botão da barra de compra e botão de “Finalizar compra”) e colocar “hover” nos botões (sem ideia, me ajuda nessa por favor..)

**Comment by arielrinnert** [comment]
Da pra fazer conforme o botão do banner da home Page.. quando passa em cima ele inverte a cor entre o texto e o fundo.. isso pode fazer pra todos os botões, com exceção dos botões do contato (Enviar) e da barra de compra pra encerrar (Finalizar Compra).. o botão da barra de compras, de adicionar ao carrinho, você pode fazer no mesmo padrão que eu comentei antes (inverter as cores do texto e do fundo.. OBS.: ficaria igual o botão de "Finalizar Compra" do carrinho)

**Comment by arielrinnert** [comment]
feito esse?

**Comment by arielrinnert** [comment]
@amedtler previsão pra esse? @roelsmich quer q a @margpm faça uma revisão nisso?

**Comment by amedtler** [comment]
Mesma coisa. Ainda não fiz. Estou seguindo as prioridades.

**Comment by amedtler** [comment]
Fiz alguns ajustes, acredito que está ok. Se tiver algo que precise ser corrigido é só avisar.

**Comment by roelsmich** [comment]
ok, não precisa se preocupar com isso agora
