### ISSUE TITLE
Home - Ajustar slider

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#107]
Ajustar tempo de transição e pausa no mouse over.

**Comment by amedtler** [comment]
Ajustado. 
Deixei a transição com 7 segundos, posso modificar se achar necessário. 
Agora está pausando quando o mouse está sob o banner. 
Além disso coloquei o recurso de passar o banner com touch (arrastando).

Obs: Talvez tenha que limpar o cache para visualizar.

**Comment by arielrinnert** [comment]
top feito!
