### ISSUE TITLE
home + blog : trocar ícone do ver mais

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#108]
Qual é o ícone?

**Comment by arielrinnert** [comment]
pode ser o ícone com o logo da ocean drop, bem personalizado mesmo..

**Comment by arielrinnert** [comment]
Cara é tipo isso, não tem padrão do que aparece quando o cara coloca o link no facebook..

![image](https://cloud.githubusercontent.com/assets/19783148/18459048/d7c5592a-793c-11e6-979b-6000f230410b.png)

**Comment by arielrinnert** [comment]
![image](https://cloud.githubusercontent.com/assets/19783148/18459071/0295984a-793d-11e6-8ab4-fdbc6dd64f21.png)

**Comment by arielrinnert** [comment]
O ideal seria que agente pudesse alterar a imagem conforme gostaríamos.. mas pelo menos uma imagem do logo e tag da empresa..
