### ISSUE TITLE
Checkout - Melhorar design do “Checkout”ocupando a faixa da direita com o resumo da compra e talvez o logo da empresa, sei lá..

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#111]

**Comment by amedtler** [comment]
Esse design não consigo modificar muito, pois o formulário é um bloco único e a parte do resumo da compra e as formas de pagamento também são um bloco único do plugin (não aconselhável modificar). 
![captura de tela 2016-08-30 as 00 34 29](https://cloud.githubusercontent.com/assets/734230/18075307/f381b706-6e49-11e6-8542-4d9e084cef74.png)

Fiz um ajuste onde coloquei aquele campo informações da nota (o único que consigo mover), para baixo do form e deixei a largura do form 100%, acompanhando a parte de baixo. 
Se tiver alguma outra ideia, avisa.

**Comment by arielrinnert** [comment]
não cara, acho q se o bloco é travado é isso ai mesmo né! fechou!
