### ISSUE TITLE
Geral - Ajustar problema de dimensões e cor do fundo das imagens do facebook quando copia um link do site e posta lá

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#113]
Pode me passar um exemplo do que acontece?

**Comment by amedtler** [comment]
Mandar url para editar o compartilhamento.

**Comment by amedtler** [comment]
Ajustei esse item, se tiver algum link com problema, peça para que me enviem a url e a imagem que deveria carregar, assim como o título e descrição da página.

**Comment by arielrinnert** [comment]
da hora Andreson! e olha só, é muita configuração em código isso ai ou agente consegue dar conta? porque se for possível acho q é melhor você explicar como faz que ficamos mais independentes e conseguimos alterar periodicamente as imagens..

**Comment by arielrinnert** [comment]
de todo modo eu já pedi pro Lucas gerar uma lista de links e imagens pra preparar lá..
