### ISSUE TITLE
Implementação Pagarme

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#114]
https://docs.pagar.me/woocommerce/

**Comment by arielrinnert** [comment]
no retorno das férias

**Comment by amedtler** [comment]
@arielrinnert, estou fazendo a integração, mas preciso da chave API Key e Encryption Key. 
Pode me passar?

**Comment by arielrinnert** [comment]
passo sim, só me explica como pfv ahhahahaha;...

de todo jeito vou te passar nosso acesso no Pagar.me

**Comment by arielrinnert** [comment]
Tem duas categorias:
- LIVE - 
  Chave de API  ak_live_dDFO3D8cRONXELOQtK10U9WBEdvL51
  Chave de criptografia  ek_live_daSBBtFTvpb37D1zNGNN9OUsMOlwR2
- TESTE - 
  Chave de API  ak_test_oV6X7nQnPHCRyyhPesfK9p7fO4pHjM
  Chave de criptografia  ek_test_Qkg48m6QrAQUZra6GTbfR2KfAmvDjO

**Comment by amedtler** [comment]
Feito. Implementado. 
Peço que faça alguns testes. 
Caso tenha algo errado, pode desativar o plugin temporariamente.

**Comment by arielrinnert** [comment]
boa! vou deixar aberto mais uns 10 dias a atividade pra irmos testando..

uma dúvida.. o checkout transparente pra parte do crédito pode ser tipo a do PagSeguro ou eles só tem aquela opção ali? 

de todo modo tem q arrumar a sobreposição da tela do cartão com o menu do site..

**Comment by amedtler** [comment]
Blz. 
Só tem essa opção. 
Quanto a sobreposição, já corrigi.

**Comment by amedtler** [comment]
Ficou ok?
