### ISSUE TITLE
Produto - Corrigir resultados das estrelas

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#116]
Não é possível alterar o resultado manualmente. O que posso fazer é colocar uma média fixa, porém quando a pessoa votar, o resultado não vai mudar, independente da nota.

**Comment by arielrinnert** [comment]
cara assim, se o sistema continuar computando as notas, de momento agente pode por uma média fixa.. ai futuramente, com a subida da nota (esperamos né, ahhahahah) reativamos o sistema.. 

dai pode por umas notas lá q variam de 4,4 a 4,8 nos produtos por favor?

valeu

**Comment by amedtler** [comment]
Consegui fazer um lance para editar manualmente os valores. Já ajustei, mas caso queira modificar é bem simples. Entre na página do produto (editar) e procure por essa parte: 

É só mudar o valor da primeira linha e salvar.

![captura de tela 2016-10-23 as 22 43 07](https://cloud.githubusercontent.com/assets/734230/19630901/5550174a-9972-11e6-9e12-dfeeedba8be6.png)

**Comment by arielrinnert** [comment]
iiirraaa isso ai!

hahaah
