### ISSUE TITLE
Checkout - Função Crédito, débito e boleto 

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#117]
Item 19 da planilha: Está aparecendo normalmente, experimente limpar o cache ou acessar de outro navegador. 

![captura de tela 2016-10-18 as 22 13 59](https://cloud.githubusercontent.com/assets/734230/19500915/339afc78-9580-11e6-88b0-70bc4cf3a92c.png)

**Comment by arielrinnert** [comment]
certo, feito!
