### ISSUE TITLE
Carrinho - Adicionar botões extras para compra de porta cápsula

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#118]
Item 6 da planilha : acho que seria legal enviar um esboço para facilitar.

**Comment by arielrinnert** [comment]
cara ta bem ttosco o desenho, mas é tipo isso:

![image](https://cloud.githubusercontent.com/assets/19783148/19602819/74a41a2e-978d-11e6-9ce8-62adbbe0ef61.png)

dois botões mais destacados "Adicionar Case Spirulina" e "Adicionar Case Chlorella"

**Comment by arielrinnert** [comment]
e ai a pagina atualiza qndo ele clica..

**Comment by arielrinnert** [comment]
@amedtler previsão pra fazer esse?

**Comment by roelsmich** [comment]
Como falado no alinhamento : o ideal seria deixar o preço total da carrinho se atualizar sozinho quando houver compra de CASES. Caso isso atrasaria o projeto muito ou poderia dar conflito por falta de testes extensivos é melhor deixar para depois da BF. 

Foi combinado que andreson ia analisar as possibilidades na quinta feira para ja conseguir iniciar o trabalho na sexta (sendo que durante o fim de semana não tera tempo suficiente disponivel para começar e finalizar a tarefa inteira.  

O imagem passado pode ser usado como desenho basico.
A arte sera fornecido pela mar na terça feira (to tentando trocar para segunda ja) e quando recebemos vamos implementar no mesmo dia ja para que tem alguns dias de teste real no site antes do BF.

**Comment by amedtler** [comment]
Fiz um teste e inicial e acho que já sei como fazer, quero ver se consigo te mostrar um esboço amanhã. 

Apenas para meu registro: https://www.themepunch.com/faq/woocommerce-include-quantity-with-add-to-cart-button/

**Comment by roelsmich** [comment]
ok

**Comment by amedtler** [comment]
Olá Michael, conforme falamos, caso aquele formato inicial demorasse muito, faria de uma forma mais simples. Para preservar o carregamento via ajax (sem recarregar a página), utilizei o padrão do carrinho do woocommerce. Nos produtos adicionais, coloquei apenas o botão de adicionar ao carrinho. Porém, perceba que nos itens do carrinho, coloquei os botões de - e + onde o usuário pode colocar mais unidades e depois disso clicar em atualizar carrinho, o que já é padrão do woocommerce. Na minha opinião, gostei mais dessa forma. A esboço ficou assim: 
![captura de tela 2016-11-20 as 22 46 40](https://cloud.githubusercontent.com/assets/734230/20467687/cceb625c-af73-11e6-9a48-77a670ab36e9.png)

**Comment by amedtler** [comment]
Obs: Esses produtos pertencem a categoria acessórios, portanto estão dinâmicos, ou seja, se adicionar outros produtos a essa mesma categoria, automaticamente vai aparecer nessa parte do carrinho. Podemos deixar limitado apenas esses dois, mas acho que a ideia é exibir outros aqui também (quando tiverem).
Obs: Caso o usuário já tenha clicado em adicionar ao carrinho  por exemplo drop case - spirulina e clicar novamente em adicionar ao carrinho, será acrescentado mais uma unidade ao produto.

**Comment by margpm** [comment]
![checkoutcase](https://cloud.githubusercontent.com/assets/23121158/20480221/c3bd5b18-afc8-11e6-9573-e144de3e39d4.jpg)

**Comment by margpm** [comment]
o azul clarinho seria inicialmente o #82d2eb (testar que não fique muito forte, para não confundir com botão ou ação)
o azul obscuro #001e9b tal vez com opacidade mais baixa (testar)

**Comment by roelsmich** [comment]
@amedtler por gentileza so deixa limitado para esses dois produtos agora. Senão vai ficar muita coisa.

**Comment by amedtler** [comment]
Os ajustes estão feitos. Já subi os arquivos. Testem em uma janela anônima, alias, isso vale para todas as alterações pois geralmente o cache demora um pouco para liberar. Podem testar em outros navegadores também ou limpar o cache do navegador.

**Comment by roelsmich** [comment]
olhei, ta ficando legal. Amanhã a mar vai fazer um ajuste nas imagens e ai vou te passar eles. 

Outra coisa: eu consigo mexer no texto/titulo? Ou preciso te passar o texto? 

@amedtler

**Comment by amedtler** [comment]
Precisa me passar o texto.

**Comment by roelsmich** [comment]
Texto para colocar em vez de "você também pode gostar disso.." 
=> 
"Leve seus drops de superpoderes com você em qualquer lugar!" 

@amedtler

**Comment by amedtler** [comment]
Alterado.
