### ISSUE TITLE
Área do cliente - Alinhar status que aparecem com os status do woocommerce

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#120]
Item 22 da planilha
ALTERAR: 
1) aguardando>>aguardando pagamento; 
2) processando>>preparando pedido; 
3) pagamento pendente>> em análise bancária; 
4) concluído>>pedido enviado; 
5) cancelado, mantém igual; 
6) reembolsado, mantém igual

**Comment by arielrinnert** [comment]
foi feito isso?

**Comment by arielrinnert** [comment]
precisa de ajuda ainda pra tocar esse?

**Comment by amedtler** [comment]
Ajustado.
![captura de tela 2016-10-24 as 23 00 22](https://cloud.githubusercontent.com/assets/734230/19669379/b0376002-9a3d-11e6-91a6-5e3dfd2381e1.png)

**Comment by arielrinnert** [comment]
show! valeu!
