### ISSUE TITLE
Blog - Display sidebar

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#127]
Item 31 da planilha: 
Display sidebar: aguardando arte e lista das categorias.

**Comment by roelsmich** [comment]
mandei mail

**Comment by roelsmich** [comment]
[Categorização Displays Blog Ocean Drop.docx](https://github.com/amedtler/oceandrop/files/547811/Categorizacao.Displays.Blog.Ocean.Drop.docx)

**Comment by amedtler** [comment]
Ok. Já tem as artes?

**Comment by roelsmich** [comment]
O documento tem um link para o drive onde estão as artes

**Comment by arielrinnert** [comment]
fluindo essa ai?

**Comment by amedtler** [comment]
Está pronto, só preciso do acesso ao ftp do blog para subir os arquivos.

**Comment by roelsmich** [comment]
registrando aqui que o acesso foi passado através de mail

**Comment by amedtler** [comment]
Implementado. Esse aqui aparece automaticamente na sidebar, abaixo dos posts mais recentes. 
Para adicionar novos displays, tanto para sidebar como para o texto, vá na opção Display no menu lateral esquerdo clique em adicionar novo. 
É só colocar o link, a imagem e marcar a categoria que é onde deve ser exibido. Lateral ou texto. 
Ficou bem fácil. Qualquer dúvida avise.

**Comment by amedtler** [comment]
Ahh! Conforme combinamos, o display do ebook está sendo exibido na sidebar, de forma randômica, junto com os demais.

**Comment by roelsmich** [comment]
show de bola
