### ISSUE TITLE
Mblog - Substituir conteúdos mais recentes pelo anterior e próximo...

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#129]
FORMATO: TEXTO> AUTOR> ANTERIOR/PRÓXIMO> COMENTÁRIOS> SIDEBAR BANNER> ANTERIOR/Próximo> RODAPÉ

**Comment by arielrinnert** [comment]
precisa de ajuda ainda pra tocar esse?

**Comment by amedtler** [comment]
Implementado. Só não foi possível colocar antes dos comentários, pois os comentários utiliza um plugin.

**Comment by arielrinnert** [comment]
boa vi lá! agora já é pro @roelsmich tocar mas vou dar um pitaco aqui, cabe a aprovação dele:
- acho q tem q destacar melhor esses botões
- seria legal ter uma foto miniatura e se possível até o título do próximo e anterior

acho q se pegasse aquele bloco de cada post q aparece na home page e fizesse uma miniatura dele pra colocar ali junto ficaria massa.. ou então colocar um em cima do outro ocupando a faixa toda se ficar muito pequeno o escrito e um quadrado..

**Comment by roelsmich** [comment]
obrigado pela sugestão @arielrinnert, bem valido mas vamos deixar isso rodando assim como MVP. Pq tem outras coisas mais urgentes agora, depois voltamos para isso.
