### ISSUE TITLE
Carrinho - Ajustar frete

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#13]

**Comment by amedtler** [comment]
Andei mexendo um pouco nessa parte, mas não lembro direito o que era para ajustar.

**Comment by arielrinnert** [comment]
então aqui é pra ter um espaço só pro usuário digitar o CEP e ai o sistema calcula o frete.. dai se possível da pra colocar aquele ícone pra clicar e ele ir pro site do correio buscar lá..

e outra coisa é que precisamos ajustar um cálculo do frete, mas esse ai deixa pra outra atividade..

**Comment by amedtler** [comment]
Isso por acaso não seria no carrinho?

**Comment by arielrinnert** [comment]
aaa sim, confundi, é isso ai.. no checkout é só ajustar o calculo com o número do correio mesmo..

**Comment by amedtler** [comment]
Ajustado

**Comment by arielrinnert** [comment]
cara, acho que esse aqui da pra construir assim: 
![ajuste frete](https://cloud.githubusercontent.com/assets/19783148/16571032/de0ee99a-4228-11e6-807b-9f763c302c1b.png)

**Comment by amedtler** [comment]
Nessa opção tirei apenas a o select do estado, mantive o valor do pac e sedex acima do campo do cep, pois para modificar isso é preciso alterar o core dos arquivos, o que não é recomendado.

**Comment by arielrinnert** [comment]
entendi, assim está tranquilo!

Vou te passar os dados do correio que encontrei aqui junto do contato da pessoa lá do correio que resolve isso ok?

Número do contrato: 9912393595
Código ADM: 16079604
SERVIÇOS CONTRATADOS:
- SEDEX 40096
- PAC 41068

Contato: tatianebrasil@correios.com.br

**Comment by amedtler** [comment]
Criei outra tarefa para a integração dos correios. #93 
Acho que pode encerrar esse item.

**Comment by arielrinnert** [comment]
ok vou encerrar essa
