### ISSUE TITLE
Geral - Arrumar Meta Description

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#130]
Item 37 da planilha

**Comment by arielrinnert** [comment]
@roelsmich viu disso?

**Comment by roelsmich** [comment]
olhei pra planilha, não percebi uma mudança de status. Olhei para a meta description no google Continua a ser errado. 

Caso precisar de algum comentario/ajuste minha, peço que tu fica mais claro @amedtler 

![schermafbeelding 2016-10-21 om 20 11 40](https://cloud.githubusercontent.com/assets/22944469/19613349/c395bbd2-97ca-11e6-9abc-b9b82d342c8e.png)

**Comment by amedtler** [comment]
Eu creio que com os ajustes que a i-goal fará, isso deve corrigir. Pode perguntar pra eles a respeito disso?

**Comment by roelsmich** [comment]
ok

**Comment by roelsmich** [comment]
Seguindo eles o ariel não fechou isso com eles. A priscila falou que ele ia ver com a equipe depois das paradas do GA e Ads. Então se tu conseguir fazer no prazo curto seria melhor você fazer sendo que é urgente e eles vão levar um tempo

**Comment by amedtler** [comment]
Ok. Vou trabalhar nisso então.

**Comment by arielrinnert** [comment]
Fluindo essa ai?

**Comment by amedtler** [comment]
@arielrinnert, @roelsmich, vou precisar de acesso admin ao google search console para ajustar essas configurações. Podem fazer isso? 
Vou deixar um link como referência, pois vou precisar para continuar os ajustes.
https://yoast.com/wordpress-seo/

**Comment by arielrinnert** [comment]
@roelsmich eu não tenho esse acesso ai q o @amedtler pediu.. vc passa aqui pfv? valeu..

**Comment by roelsmich** [comment]
@amedtler feito

**Comment by amedtler** [comment]
Não entendi. Está ok?

**Comment by roelsmich** [comment]
@amedtler eu adicionei seu mail como usuario no Google Search Console. O convite chegou?

**Comment by amedtler** [comment]
Não recebi o convite.

**Comment by roelsmich** [comment]
te adicionei de novo como usuario la. entra la no site e tenta de novo pf

**Comment by amedtler** [comment]
Consegui acessar e já fiz alguns ajustes. Agora vou acompanhar para ver se deu certo. Valeu!

**Comment by roelsmich** [comment]
@amedtler parece que não deu certo. Você consegue tentar de alguma outra forma?

**Comment by amedtler** [comment]
Realmente, ainda não deu certo. Vou tentar outra coisa.

**Comment by roelsmich** [comment]
para ficar registrado, segue aquele parte no codigo que mencionei no mail 
![schermafbeelding 2016-11-22 om 18 57 32](https://cloud.githubusercontent.com/assets/22944469/20844319/56e9cdbe-b8a6-11e6-9fae-3e3141133851.png)

**Comment by amedtler** [comment]
Fiz outro ajuste, agora vou monitor para ver se deu certo.

**Comment by roelsmich** [comment]
parece que deu certo 👍
