### ISSUE TITLE
Segmentação Checkout

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#137]
Segmentar o processo do Checkout em diferentes etapas para que conseguimos pegar os dados essenciais do lead (mail, nome,...) o quanto antes. Isso para que conseguimos contatar os leads que desistiram do finalizar a compra na parte do pagamento. 

O ideal seria criar um evento de conversão quando a pessoa envia os dados da primeira etapa. 
Assim consigo usar-lo como gatilho para os fluxos do RD.

Para mais informações, consulta @arielrinnert

**Comment by roelsmich** [comment]
O que você colocou no mail, sugerindo a botão "continuar" como gatilho para envio, acho uma boa

**Comment by arielrinnert** [comment]
@roelsmich atividade #122
