### ISSUE TITLE
Trocar wp-admin para outro nome

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#138]

**Comment by amedtler** [comment]
Implementado. Agora devem acessar https://oceandrop.com.br/painel-admin 
Caso alguém tente acessar utilizando wp-admin ou wp-login.php é redirecionado para página 404.

**Comment by arielrinnert** [comment]
feito! mas só pra confirmar.. é só o painel de acesso q muda o endereço né? pq depois q faz o login o endereço padrão é o wp-admin mesmo..

**Comment by amedtler** [comment]
Exatamente.

**Comment by arielrinnert** [comment]
feito!
