### ISSUE TITLE
Problema com posts sugeridos no blog

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#139]
Quando entrar em qualquer pagina com blogpost, os blogposts sugeridos que deveriam aparecer no canto direito aparecem abaixo dos comentarios

**Comment by arielrinnert** [comment]
@amedtler esse problema tem relação com a atividade https://github.com/amedtler/oceandrop/issues/129 ?

**Comment by amedtler** [comment]
Não tem relação, inclusive não entendi porque aconteceu isso, já que não mexi nessa parte. 
Tentei corrigir ao meio dia mas não deu tempo, vou fazer agora.

**Comment by amedtler** [comment]
Corrigido

**Comment by amedtler** [comment]
Aproveitando, preciso do acesso FTP do blog. Podem me passar?

**Comment by arielrinnert** [comment]
@roelsmich vc tem o FTP do blog né?

**Comment by roelsmich** [comment]
pior que não

**Comment by roelsmich** [comment]
e o problema foi resolvido, eu vou encerrar a tarefa

**Comment by roelsmich** [comment]
o blog não ta no mesmo dominio do que o site? não da com o FTP do site? 
@amedtler

**Comment by amedtler** [comment]
O blog é um subdomínio, não tenho acesso. Posso até acessar com os mesmos dados, mas preciso de permissão.
