### ISSUE TITLE
Colocar popup no blog

### ISSUE THREAD

**Issue by arielrinnert** [amedtler/oceandrop#140]
Confirmado com a i-goal, por R$ 100,00 a mais rola colocar..

Eles solicitaram: 
- e-book (@roelsmich posta aqui pfv..)
- arte do popup (@roelsmich esse é uma demanda que vai pra @margpm, priorização é com vcs..)

**Comment by roelsmich** [comment]
Pop-up sera internalizado, e consigo implementar sozinho (@margpm fornece a arte)

**Comment by roelsmich** [comment]
@arielrinnert o que exactamente você precisa? O pdf do e-book ou o landing page do e-book? 

e sobre a arte: precisamos de mais info: quais as limitações? Quais serão as botões? Como sera o conteudo? A gente precisa fornecer o conteudo? 
Deve ser mais especifico
