### ISSUE TITLE
Bug pagina carrinho

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#141]
Quando estiver na pagina do carrinho, o link/botão no cabeçalho "contato" não funciona.

**Comment by amedtler** [comment]
Ajustado.

**Comment by roelsmich** [comment]
Andreson talvez não expliquei certo. Quando estivar na pagina do carrinnho e clicar botão contato no cabeçalho, o site te joga para o rodapé da pagina. Mais ai não tem informações de contato ou formulario de contato. 

Qual seria a solução? Implementar o formulario e dados de contato no rodapé?

**Comment by amedtler** [comment]
Na verdade é isso mesmo. Esse tipo de comportamento é utilizado por todos os sites. Quando o cliente estiver na página do carrinho e checkout, não pode ter nenhuma distração, link, etc... é comprovado que dessa forma as conversões são maiores.

**Comment by arielrinnert** [comment]
então @roelsmich boto fé no q vc ta falando.. mas é isso ai q o Andreson falou, o padrão é clean pro carrinho e pro checkout.. a zica é q o nosso menu é padrão pra todas as páginas e por isso fica o problema.. o que eu vejo como solução, inclusive pras outras páginas pq não acho uma experiencia legal "arremessar" o usuário até o rodapé, é abrir o chat (do Zopin por exemplo) ao invés de falar pelo rodape..

qq vc acha @roelsmich ?

**Comment by amedtler** [comment]
Acho legal essa ideia também @arielrinnert.

**Comment by roelsmich** [comment]
Acho uma boa, vamos fazer assim. Quando chegarmos na tarefa de implementar o ZOPIN podemos finalizar este tarefa

**Comment by arielrinnert** [comment]
@roelsmich minha sugestão pra implementar o Zopin:
- eu não avancei nisso ainda pq acredito q se não for feita uma gestão bem feita não tem nem pq implementar (ok podemos testar mas me parece claro q vai surgir demanda dai..)
- a solução q vejo pra isso é centralizar o atendimento ao cliente numa plataforma única, q hoje vejo o Zendesk como ideal pra isso (apesar de não conhecer muito bem ele, e menos ainda outras soluções do mercado)
- eu já falei diversas vezes pro Lucas e dps pra Ju se agilizarem com isso mas até agora nada (eles tem coisa q chega já pra fazer e tão postergando..)
- logo: passa pra Ju um deadline pra ferramenta ser implementada e cadastra direto as contas dela no Zopin (falecom@ e juliana@).. assim ela vai receber as demandas de qualquer modo, organizada ou não, mas dai vai ser problema dela se preparar pra isso..

**Comment by arielrinnert** [comment]
depois marca essa sugestão lá na atividade do zopin só.. ahhahaha

**Comment by amedtler** [comment]
Com a implementação do zendesk chat ficou ok?

**Comment by roelsmich** [comment]
ficou, vamos encerrar
