### ISSUE TITLE
Migrar servidor (Hyann para um próprio)

### ISSUE THREAD

**Issue by arielrinnert** [amedtler/oceandrop#144]
Essa atividade ia ser executada pelo Hyann quando íamos usar o AWS da Amazon mas isso não vai mais acontecer..

o @amedtler vai nos avisar quando a hostgator abrir uma promoção lá para os servidores deles, nós faremos a aquisição e então a migração.

**Comment by roelsmich** [comment]
@amedtler você que trabalha com o nosso servidor poderia nos dar uma sugestão qual seria o nosso necessidade de capacidade do servidor? Ou ao menos o que levar em conta?

**Comment by amedtler** [comment]
A promoção vai iniciar dia 24/11, até 28/11, 50% de desconto. 
O próprio suporte da hostgator faz a migração. 
No plano atual, vocês sentem necessidade de algo a mais? 
Acho que poderiam continuar usando um plano de hospedagem compartilhada e mais pra frente se for necessário, podem fazer um upgrade.

**Comment by roelsmich** [comment]
Então não sei qual o nosso plano atual, nem sei qual as metricas usados. Pedi mais informações ao Hyann.

**Comment by roelsmich** [comment]
@amedtler eu dei uma olhada no plano basico e se entendi bem não ha problema pra migrar o blog também né? sendo que é um subdominio. Vc pode confirmar isso?

**Comment by amedtler** [comment]
Amanhã 24/11 a partir das 12h, a promoção vai estar valendo. 
Indico o plano de hospedagem Business que além de ter um ótimo limite de banda, etc, já tem SSL privado. 
Vai estar custando R$719, 82 para o plano Trienal (válido por 3 anos).
