### ISSUE TITLE
Ajustar botões na pagina principal "adicionar NO carrinho" para "adicionar AO carrinho"

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#147]

**Comment by amedtler** [comment]
Ajustado.

**Comment by roelsmich** [comment]
@amedtler ta aprovado mas vi que as botões "adicionar ao carrinho" nos cases desapareceram. 
Acho que isso tem a ver com a ajuste que fez. Você pode resolver isso por favor?
