### ISSUE TITLE
Problema na descrição boxes

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#148]
A palavra "dias" aparece no fim da descrição da duração dos 4 boxes na pagina inicial. 

Entrei nas configurações mas não consegui achar o problema. 
![schermafbeelding 2016-11-18 om 13 06 11](https://cloud.githubusercontent.com/assets/22944469/20434668/0cd24650-ad90-11e6-892d-b7ddba55f9ee.png)

**Comment by amedtler** [comment]
Ajustado.
