### ISSUE TITLE
Home - Incluir faixa de fotos de produtos [antes da promessa da marca]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#15]

**Comment by amedtler** [comment]
??

**Comment by arielrinnert** [comment]
é uma faixa de foto esticada, tipo aquela q tem na página de produtos, que vai aparecer ali na Home tbm.. to esperando a Mar dar um grau nas imagens.. mesma coisa da atividade https://github.com/amedtler/oceandrop/issues/32

**Comment by arielrinnert** [comment]
Pode posicionar essa antes da faixa "Subscribe"

é a imagem "Home 02" na pasta https://drive.google.com/drive/folders/0B0VHhFX-xi3KWHpMU2p1NkdabTA

**Comment by amedtler** [comment]
Implementado.

**Comment by arielrinnert** [comment]
feito
