### ISSUE TITLE
Ajustar e-commerce com requisitos da Camara-e.net

### ISSUE THREAD

**Issue by arielrinnert** [amedtler/oceandrop#150]
_Nesse sentido, verificamos que os requisitos abaixo descritos não estão sendo atendidos conforme as exigências legais:_
- **Ausência de CNPJ no site da loja;
- Ausência da Razão Social no site da loja;
- Ausência ou divergência de endereço físico – conforme consta na Receita Federal;**

_Sugerimos fazer os ajustes necessários, informando-nos em resposta a este e-mail, com o print da tela constando as alterações. 
Qualquer dúvida, estamos à disposição._

**Comment by arielrinnert** [comment]
@roelsmich seguinte: eu fiz alterações emergenciais porque ai eles liberam ainda o sela do Black Friday Legal pra nós.. Coloquei no e-commerce essas informações no Rodapé que aparece na Home Page ou na página dos Produtos, preciso que o @amedtler coloque urgentemente isso no rodapé do carrinho e checkout tbm (e qualquer outra página..)

posteriormente agente arruma design e etc.. ok?

**Comment by arielrinnert** [comment]
![print ajustes ocean drop](https://cloud.githubusercontent.com/assets/19783148/20532311/ae6dad8c-b0c0-11e6-8c8c-5cc1db86cf06.png)

Ficou assim..

**Comment by roelsmich** [comment]
@amedtler acredito que você facilmente pode deixar as infos na mesma padrão (fonte, cor, tamanho,...) do que o resto da informação no rodapé né?

**Comment by arielrinnert** [comment]
@roelsmich e @amedtler reforçando pra colocar nos rodapés das outras páginas tbm..

**Comment by amedtler** [comment]
Ajustado. 
Tomei a liberdade de colocar o texto de uma forma mais harmônica/discreta no footer principal. 
Também coloquei no footer do carrinho, checkout e demais páginas. 
Obs: Não esqueçam de limpar o cache.

![captura de tela 2016-11-22 as 21 28 03](https://cloud.githubusercontent.com/assets/734230/20546184/c9fb4a0c-b0fa-11e6-91d5-e5ba79d1c1de.png)

![captura de tela 2016-11-22 as 21 28 24](https://cloud.githubusercontent.com/assets/734230/20546188/d3cc592c-b0fa-11e6-94bd-3a51b37fc6e6.png)

**Comment by roelsmich** [comment]
show
