### ISSUE TITLE
URGENTE: REMOVER ARIEL DAS ATIVIDADES QUE NÃO PRECISAM DA INTERVENÇÃO DELE..

### ISSUE THREAD

**Issue by arielrinnert** [amedtler/oceandrop#151]
Favor remover meu usuário como padrão nas atividades do git, não aguento mais receber e-mail kkkk

**Comment by arielrinnert** [comment]
@roelsmich continuo recebendo email pra qualquer coisa q aconteça no git..

@amedtler sabe como alterar essa configuração?

**Comment by roelsmich** [comment]
@arielrinnert tem aquela botão "unsubscribe", tem que clicar isso. Pq vc sera notificado cada vez que for mencionado num comentairo
![schermafbeelding 2016-11-25 om 15 29 27](https://cloud.githubusercontent.com/assets/22944469/20632346/ff292c00-b323-11e6-93bd-101df47ae591.png)
