### ISSUE TITLE
Colocar sele do Camara-e e Black Friday Legal no ar

### ISSUE THREAD

**Issue by arielrinnert** [amedtler/oceandrop#152]
@roelsmich e @amedtler

a atividade https://github.com/amedtler/oceandrop/issues/150 vai gerar esta demanda ..

Assim que estivermos devidamente cadastrado, eles liberam os códigos pra incluirmos estes selos de credibilidade no e-commerce.. tem que alinhar o aparecimento dos selos com o início das nossas campanhas tbm..

tem q dar uma pensada na distribuição deles mas penso em algo próximo ao selo do Site BLindado (pelo menos aquele que aparece no rodapé..), só tem q lembrar q o selo do Black Friday sai logo do ar, ao mesmo tempo que ele pode ter bastante destaque nas fases em q estiver valendo..

Segue o link pra vcs verem os dois selos novos.. http://blackfridaylegal2016.com.br/registro/index/?mpenav=1

**Comment by roelsmich** [comment]
@arielrinnert não consigo ver os selos, consegue mandar um printscreen?

**Comment by roelsmich** [comment]
Sobre o posicionamento do selo, acho valido sempre aparecer ao lado do site blindado. Também no carrinho onde o selo do site blindado aparece bem visivel.

**Comment by arielrinnert** [comment]
![](http://blackfridaylegal2016.com.br/temas/front/img/blackfriday-legal-2016-vertical.png)

**Comment by arielrinnert** [comment]
![](http://tibahia.com/upload/images/2014-06-03/20140603090346_Camara-Enet-Selo-Clique-e-Confie.jpg)

**Comment by arielrinnert** [comment]
daqui a pouco eles liberam os selos e eu posto a API aqui..

**Comment by amedtler** [comment]
Aguardando script para integração dos selos.

**Comment by roelsmich** [comment]
ainda esperando o script para o selo da e-camada

**Comment by arielrinnert** [comment]
```
> Instalar o selo Clique e-Valide é muito simples.
> 
> Solicite para seu webmaster copiar e colar o código abaixo dentro das tags <body></body> de todas as páginas de seu site. Pronto! Seus clientes já podem confiar que seu site foi validado e faz parte do Movimento e-PME da camara-e.net.
> 
> <!-- Acrescente esta div em um local desejado desde que esteja entres as tags <body> e </body> -->
> <div id="cliqueevalide"></div>
> 
> <!-- Inicio Selo cliqueevalide.com.br -->
> <script src="//www.cliqueevalide.com.br/js/selo-cliqueevalide.js" type="text/javascript"></script>
> <!-- Fim do Selo cliqueevalide.com.br -->
> 
> PARA MAIORES INFORMAÇÕES LIGUE: (11) 3237-1102
```

**Comment by arielrinnert** [comment]
ACESSO:

http://www.cliqueevalide.org.br/
-login ariel@oceandrop.com.br
-senha admbrastax1

**Comment by amedtler** [comment]
Implementado. 
Ao acessar pode ter cache. Isso vale para todas as alterações que forem feitas. 
Favor abrir em uma aba anônima para validar.

**Comment by arielrinnert** [comment]
selo feio né! kkkkk

feito..
