### ISSUE TITLE
problema status do pedido

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#155]
Acabamos de descobrir que o status do pedido que esta em "aguardando pagamento" ou "processando" as vezes muda sozinho para "enviado". 
Você pode verificar o que esta causando isso? 

obs. vemos que depois de um tempo o status volta para "aguardando pagamento" 
No anexo 2 leads com quais aconteceu isso
![aaaa](https://cloud.githubusercontent.com/assets/22944469/20562170/6f9aeda0-b169-11e6-9024-51e26f9000cf.png)

**Comment by amedtler** [comment]
Acho que vamos deixar isso para depois da black friday.

**Comment by amedtler** [comment]
Ajustado. Favor conferir e avisar caso volte a acontecer.

**Comment by arielrinnert** [comment]
sabe o que pode ter acontecido Andreson?

**Comment by arielrinnert** [comment]
tirei a prioridade..

**Comment by amedtler** [comment]
Estava faltando um ponto e vírgula em uma função javascript.

**Comment by roelsmich** [comment]
@amedtler segundo o ariel o problema continua

**Comment by amedtler** [comment]
@roelsmich,@arielrinnert, esse problema ocorre quando vocês fazem alguma ação, ou isso acontece do nada? Podem me dar mais detalhes?

**Comment by roelsmich** [comment]
o ariel esta de ferias, eu vou verificar com o time porque eu nao estava monitorando isso

**Comment by roelsmich** [comment]
@amedtler segundo o ariel a alteração foi feito sempre por causa do pagseguro. Entao vou encerrar aqui
