### ISSUE TITLE
ajuste ortografico

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#157]
na pagina principal tem o erro que em todos os produtos a palavra "cápsulas" aparece como "capsulas". 
![schermafbeelding 2016-12-02 om 23 01 38](https://cloud.githubusercontent.com/assets/22944469/20855427/fee59be6-b8e3-11e6-9b20-b90f173051e1.png)

**Comment by amedtler** [comment]
Ajustado.
