### ISSUE TITLE
criar pagina tabelas nutricionais 

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#159]
queremos uma pagina que contém as tabelas nutricionais dos produtos 
Deve ser acessivel atraves do menu dropdown
'+ um botão na pagina do produto

**Comment by roelsmich** [comment]
eu vou solicitar as tabelas e o conteudo com lucas o quanto antes

**Comment by roelsmich** [comment]
[Tabela_Nutricional.pdf](https://github.com/amedtler/oceandrop/files/655675/Tabela_Nutricional.pdf)
segue a tabela

**Comment by roelsmich** [comment]
Se puder deixar um campo de titulo e um campo de texto acima e abaixo da tabela para nos incluir texto caso necessario seria bom

**Comment by amedtler** [comment]
Também preciso da arte para essa página.

**Comment by roelsmich** [comment]
@amedtler não entendi o que você precisa de arte? Seria um pagina "basico" com a tabela nutricional como conteudo + um campo de titulo + campo de texto. 

Caso precisar algo mesmo, pode explicar mais detalhado?

**Comment by amedtler** [comment]
Página criada. 
https://oceandrop.com.br/tabelas-nutricionais/ 
Para inserir mais conteúdos é só editar a página. 
Obs: Lembrando que o conteúdo ficou como imagem, pois o material veio como pdf.
