### ISSUE TITLE
pagina FAQ

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#160]
criar pagina de FAQ, acessivel pelo menu dropdown. 

te passo o conteudo o quanto antes

**Comment by roelsmich** [comment]
@amedtler so vão entregar o conteudo semana que vem, então se puder deixar a pagina pronto até onde der seria bom

**Comment by roelsmich** [comment]
O conteudo sera enviado sabado de tarde @amedtler

**Comment by lucasmarder** [comment]
Fala @amedtler estou anexando o conteúdo do FAQ - Não sei como é exatamente a configuração da página, mas fiz uma breve introdução e abaixo temos 15 perguntas.  Qualquer dúvida é só chamar.

**Comment by lucasmarder** [comment]
[FAQ-2.0.docx](https://github.com/amedtler/oceandrop/files/659102/FAQ-2.0.docx)

**Comment by amedtler** [comment]
Pessoal, não estou sabendo dessa página. Tem alguma arte?

**Comment by roelsmich** [comment]
@amedtler ola andreson, é por isso que queria alinhar contigo antes do FDS ainda hehe. 
Seria um pagina normal, so precisa incluir o conteudo que o lucas passou. Pode deixar tudo pronto para quando o menu dropdown sera pronto, nesse momento colocaremos no ar

**Comment by amedtler** [comment]
Pessoal, essa página já existia, já tinha feito quando o @arielrinnert estava tomando conta. 
https://oceandrop.com.br/perguntas-frequentes/ 
Tem uma opção no menu lateral FAQ. Basta cadastrar a pergunta e a resposta. 
Acho que dessa forma fica melhor.
