### ISSUE TITLE
frete gratis dia 21/12

### ISSUE THREAD

**Issue by roelsmich** [amedtler/oceandrop#161]
no inicio de verão queremos dar frete gratis para quem efetua uma compra. Porém somente para o PAC. 

A gostaria de saber se é possivel você programar a opção PAC - FRETE GRÁTIS HOJE no site e abaixo o SEDEX pra quem quiser e calcular normalmente. 

consegue fazer isso?

**Comment by amedtler** [comment]
Tem a opção de frete grátis que pode ser habilitado. 
No caso tiraríamos o PAC e deixaríamos frete grátis e sedex. Também é possível aumentar o prazo de entrega para o frete grátis, caso seja necessário.

**Comment by roelsmich** [comment]
então mas não é possivel deixar  o PAC para as pessoas que querem usa-o?

**Comment by amedtler** [comment]
Pode deixar, sem problemas. Mas como o PAC será o frete grátis, não vejo porque deixar os dois. Vocês que sabem. Além disso, o frete grátis vai estar disponível para qualquer compra ou somente acima de um valor determinado?

**Comment by roelsmich** [comment]
sim o frete gratis seria para o site todo
A razão porque nos ainda queremos manter o sedex ativo é que queremos deixar a opção do produto chegar mais rapido para quem é disposto a pagar mais.

**Comment by roelsmich** [comment]
so lembrando: você ativa no dia 21 e desativa depois de meia noite então

**Comment by roelsmich** [comment]
@amedtler esqueci de te dizer : tem que trocar o banner também (não vou conseguir fazer pq não estarei em casa). Coloquei o banner em anexo, deve aparecer como o primeiro banner e não precisa de botão. Depois de 24h vai ter que apagar o banner (junto com a parada do frete) 
![bannerveraopromofinal](https://cloud.githubusercontent.com/assets/22944469/21366500/31f902d8-c6e1-11e6-8900-8e3d06e16fdb.png)

**Comment by amedtler** [comment]
Implementado.

**Comment by amedtler** [comment]
Bom dia! 

A pedido do @lucasmarder, os cupons foram desativados. 
Pessoal é bem simples fazer isso, vou explicar para que saibam fazer para os próximos. 

Menu lateral do painel-admin, opção woocommerce/configurações, aba finalizar compra. 
Primeira opção, habilitar o uso de cupons. É só clicar no check para habilitar ou deixar vazio para desabilitar.
