### ISSUE TITLE
Produto - Incluir faixa de fotos de produtos [antes do blog]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#17]

**Comment by arielrinnert** [comment]
Essa faixa fica abaixo da faixa de "Apoio ao consumo" e acima da faixa do "Blog"

**Comment by arielrinnert** [comment]
Fotos estão nessa pasta:  https://drive.google.com/drive/folders/0B0VHhFX-xi3KWHpMU2p1NkdabTA
- Página da Spirulina = "Spirulina 02"
- Página da Chlorella = "Chlorella 02"
- Página da PowerBox = "Power Box 02"

**Comment by arielrinnert** [comment]
feito
