### ISSUE TITLE
Produto - Ajustar apresentação dos produtos

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#18]

**Comment by amedtler** [comment]
O que era pra ser feito nos produtos?

**Comment by arielrinnert** [comment]
a ideia é fazer a apresentação inicial ficar com essa cara abaixo, já com a pontuação por estrelas..
acho q o ideal é agente fazer um call pra alinhar certinho essa mudança ai..

![apresentacao produtos](https://cloud.githubusercontent.com/assets/19783148/16570985/0670922c-4228-11e6-80b3-20b91c154f98.png)

**Comment by amedtler** [comment]
Ok. Podemos marcar.

**Comment by arielrinnert** [comment]
conversamos hj já sobre isso ok?

**Comment by amedtler** [comment]
Só pra lembrar... vai ficar esse padrão que tu colocou acima ou vai ser diferente?

**Comment by arielrinnert** [comment]
fica como está acima mesmo..

**Comment by arielrinnert** [comment]
só as estrelas ali tem q ajustar p/ cara poder votar e tbm pra aparecer a nota média da pontuação..

**Comment by amedtler** [comment]
Ajustado. Não esquece de limpar o cache para visualizar os ajustes. Apenas atualiza a página uma ou duas vezes.

**Comment by amedtler** [comment]
Aguardando aprovação.

**Comment by arielrinnert** [comment]
ta ficando bem legal! amanhã vejo contigo como q é o funcionamento certinho e ai te passo um feed back..

**Comment by amedtler** [comment]
Ok

**Comment by amedtler** [comment]
Aquele bug que comentou no skype (imagem quebrando) é porque o tamanho da imagem precisa ser 414x414px. Tem como criar um padrão, porém quando se cria um padrão específico o sistema cria uma nova imagem de todas as images existentes com esse tamanho, então acho que não tem necessidade, já que são poucos produtos. Já corrigi todos no site. Além disso, quando o produto não tem estoque, escondi o botão adicionar ao carrinho da compra fixa (lateral fixa).

**Comment by amedtler** [comment]
Outro item relacionado a essa página: deixar a compra fixa rolar mais... ajustado.

**Comment by amedtler** [comment]
Sobre o ranqueamento (estrelas), não é possível inverter conforme vocês tinham solicitado. Adicionei a informação da média abaixo, onde também não é possível colocar acima. Mas dessa forma acho que já fica mais fácil de entender. Além disso, troquei as estrelas, pois aquelas outras estavam com pouca qualidade para aumentar o tamanho (se quiser mudar as estrelas, pode me mandar a arte conforme o padrão em anexo, pode ser uma em cada arquivo tamanho 60x60px), também aumentei o tamanho dos ícones de compartilhamentos, conforme solicitado. 
Obs: no hover das estrelas mostra quanto vale. 
![padrao-estrelas](https://cloud.githubusercontent.com/assets/734230/17829453/becc6a36-6685-11e6-9e03-c8f3b1a3191b.jpg)

**Comment by amedtler** [comment]
Troquei de lugar os ícones (anvisa, etc...) coloquei abaixo da primeira imagem, conforme solicitado.Também ajustei novamente o tamanho dos selos das vantagens.

**Comment by arielrinnert** [comment]
cara ta ficando bem da hora! só tenho sugestões quanto as estrelas mesmo.. 
- o formato e design ta ok
- já q não da pra inverter´, paciência, com a média ali já ajuda bastante
- seria legal, em cima das estrelas, colocar um "Vote agora" quando o cara não votou e um "Votado 'checked' " (o 'checked' no caso é aquele símbolo de marcado, em anexo..).. é possível? pois acho q é a unica coisa q ainda pode dar confusão..
- e ai outra coisa é o seguinte, ele poderia "zerar" as estrelas quando o cara ainda não votou e passa o cursor em cima pra votar... e ai sim ir enchendo as estrelas conforme ele vai colocando o cursor nas estrelas de baixo.. é possível? pq por exemplo na chlorella, como tem 5 estrelas na votação, o cara passa o cursor em cima e parece q não acontece nada, só ta mudando o escrito lá embaixo..
- tem q padronizar o texto da média pra aparecer sempre só o resultado final da média, conforme é quando o cara já votou..
- e vc pode computar uns 50 votos ali no sistema? com notas q deem uma média de 4,8 +- kkkk é bom né pra pegar uma moral!

**Comment by arielrinnert** [comment]
a e só da apresentação ainda o seguinte, os selos ali q vc colocou abaixo da foto quadrada, só inverte o distanciamento entre os blocos... aproxima eles da foto quadrada e afasta do "banner" esticado..

**Comment by arielrinnert** [comment]
exemplo checked https://pbs.twimg.com/profile_images/297482557/600px-Green_check.svg.png

**Comment by amedtler** [comment]
Ajustado. Única coisa é que não consigo "zerar" as estrelas quando já tem voto, mesmo que o visitante não tenha votado. Mas para resolver, aparece o texto de vote agora e a média abaixo. 
Também modifiquei a imagem do hover, assim é mais fácil de diferenciar. 
Com isso, ficou tudo como pediu. 
Ah! E sobre os votos... não tenho como computar. hehehe

**Comment by arielrinnert** [comment]
top, feito!
