### ISSUE TITLE
Home - Remover imagem da forma de pagamento 

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#2]

**Comment by amedtler** [comment]
Removido

**Comment by arielrinnert** [comment]
Então Andreson, pra tirar as formas de pagamento daqui, é importante colocá-las no rodapé, pois é requisito do Google Shopping que isto esteja visível em todas as páginas. Dai não sei se você quer colocar de volta ou prefere colocar direto no rodapé.. no documento da Catarinas tem um modelo aprovado para as formas de pagamento no rodapé, com os ícones em branco assim como o restante do rodapé..

**Comment by amedtler** [comment]
Ok, vou verificar e ajustar.

**Comment by amedtler** [comment]
Não consegui localizar essa arte, pode me mandar o arquivo/link?

**Comment by amedtler** [comment]
Coloquei de volta até resolvermos isso.

**Comment by amedtler** [comment]
Removido

**Comment by arielrinnert** [comment]
Certo
