### ISSUE TITLE
Carrinho - Incluir imagem de certificado SSL  e Site BLINDADO

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#24]

**Comment by amedtler** [comment]
Selo adicionado. Porém não sei se está no lugar certo. Como disse anteriormente, tem vários ajustes referente ao rodapé, seria bom ter uma arte completa com todos os ajustes, assim matamos tudo de uma vez. Além disso, qual seria a imagem referente ao certificado SSL, tens ela?

**Comment by arielrinnert** [comment]
Cara vamos redesenhar esse rodapé então.. acho que o backgroud está tranquilo.. amanhã ou sexta no máximo eu faço o desenho e te passo ok?

**Comment by arielrinnert** [comment]
Cara vou passar aqui o posicionamento geral dos selos do Site Blindado:
- Home Page, só no rodapé por enquanto;
- Pg Produtos, no rodapé e também na caixa de compra fixa da direita;
- Carrinho, no rodapé e também em cima da tabela de detalhamento do pedido, ao lado do texto "Carrinho".. pode aparecer assim: "Carrinho - Você está em um ambiente seguro! [selo do Site Blindado]
- Checkout, no rodapé e também ao lado do texto "Checkout".. pode aparecer assim: "Checkout - Você está em um ambiente seguro! [selo do Site Blindado]

Dai acho que fica bom por hora..

**Comment by amedtler** [comment]
Implementado.

**Comment by arielrinnert** [comment]
Andreson aqui é possível fazermos como eu comentei acima antes de eu fechar a atividade?

"Carrinho - Você está em um ambiente seguro! [selo do Site Blindado]

**Comment by amedtler** [comment]
Já tinha feito, esqueci de subir o arquivo. Pode conferir.

**Comment by arielrinnert** [comment]
Da hora isso ai! Só assim, é possível manter a primeira palavra (Carrinho e Checkout) em destaque? Tipo negrito ou em Caixa alta? um dos dois ou os dois, como ficar melhor.. assim parece que ficou um pouco confuso..

**Comment by amedtler** [comment]
Feito, ajustado. Dá uma olhada.

**Comment by arielrinnert** [comment]
top, isso ai!
