### ISSUE TITLE
Checkout - Remover rodapé

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#27]

**Comment by amedtler** [comment]
Removido

**Comment by arielrinnert** [comment]
Show de bola, mas o rodapé saiu das páginas dos produtos também, ali acho que seria legal manter ainda.. qq você diz?

**Comment by amedtler** [comment]
Ajustado, agora muda o rodapé somente no checkout e carrinho. Falando nisso, eu coloquei um estilo qualquer, tem alguma arte para esse outro modelo de rodapé?

**Comment by arielrinnert** [comment]
Ta legal assim
