### ISSUE TITLE
Rodapé - Incluir imagem de certificação SITE BLINDADO

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#29]

**Comment by amedtler** [comment]
Selo adicionado. Porém não sei se está no lugar certo. Como disse anteriormente, tem vários ajustes referente ao rodapé, seria bom ter uma arte completa com todos os ajustes, assim matamos tudo de uma vez.

**Comment by arielrinnert** [comment]
Cara vamos redesenhar esse rodapé então.. acho que o backgroud está tranquilo.. amanhã ou sexta no máximo eu faço o desenho e te passo ok?

**Comment by arielrinnert** [comment]
Andreson, eu vi naquele manual de instrução da Site Blindado, em power point, que tem exemplos do selo em estampas coloridas com o fundo transparente.. é bem na área que explica sobre a distribuição no rodapé. Você pode pedir pra eles as instruções pra fazer no nosso assim tbm?

**Comment by arielrinnert** [comment]
![desenho rodape](https://cloud.githubusercontent.com/assets/19783148/16391848/573092c4-3c7f-11e6-990a-e61866bed4d7.jpg)

**Comment by arielrinnert** [comment]
Andreson aqui estão as imagens das formas de pagamento e do certificado SSL em branco.

![visa](https://cloud.githubusercontent.com/assets/19783148/16427975/40f51846-3d46-11e6-8d75-5e94800748c7.png)
![boleto](https://cloud.githubusercontent.com/assets/19783148/16427977/4119b354-3d46-11e6-97c2-cbcf43643e8c.png)
![elo](https://cloud.githubusercontent.com/assets/19783148/16427978/412c97a8-3d46-11e6-8b20-726f8b3a4ca3.png)
![formas de pagamento](https://cloud.githubusercontent.com/assets/19783148/16427979/4134ae34-3d46-11e6-8873-7c167accaec3.png)
![mastercard](https://cloud.githubusercontent.com/assets/19783148/16427980/4134acea-3d46-11e6-93f8-9dfd1ca621d4.png)
![pagseguro](https://cloud.githubusercontent.com/assets/19783148/16427981/4137bfa2-3d46-11e6-9ff4-47ce665688c8.png)
![paypal](https://cloud.githubusercontent.com/assets/19783148/16427982/4137de7e-3d46-11e6-9f84-9589238977d1.png)
![ssl](https://cloud.githubusercontent.com/assets/19783148/16427983/413cd5e6-3d46-11e6-8501-92bc699d0e6a.png)

**Comment by amedtler** [comment]
Ariel, tem certeza que pode utilizar o selo SSL blindado? Parece ser um serviço diferente do selo site blindado. Enfim, só para ter certeza. O rodapé está pronto, mas ainda não subi os arquivos, vou aguardar esse retorno primeiro.

**Comment by arielrinnert** [comment]
Cara pode deixar esse certificado do SSL por fora agora, só o do Site Blindado ta bom. Vou confirmar certinho qual a nossa servidora de SSL, mas de todo jeito nós temos o SSL do Site Blindado a disposição pra instalar, deve valer a pena né?

**Comment by amedtler** [comment]
Ok. Está ok, porém agora a noite não está aparecendo o selo, o código é o que eles me passaram, se não aparecer mais vou entrar em contato com o suporte.

**Comment by amedtler** [comment]
Já voltou. Tudo ok.

**Comment by arielrinnert** [comment]
feito
