### ISSUE TITLE
Home - Incluir testimonials

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#3]

**Comment by amedtler** [comment]
Aguardando arte

**Comment by arielrinnert** [comment]
A Mar me prometeu entregar amanhã. Assim que tiver na mão te mando..

**Comment by amedtler** [comment]
Já recebeu essa arte?

**Comment by arielrinnert** [comment]
Cara recebi umas versões da Mar q não curti muito até agora, pedi uma última agora p ela, chegando te passo.

**Comment by arielrinnert** [comment]
Aqui está o link com as imagens:
https://drive.google.com/drive/folders/0B0VHhFX-xi3Kd09yY1d2ajhsVXM

**Comment by amedtler** [comment]
Implementado. No painel admin tem a opção Testimonials. 
Ficou bem fácil de colocar as informações, já pode colocar. 
Só vai aparecer a partir do momento em que colocar o primeiro depoimento, além disso, se tiver só um depoimento, não vai aparecer as setas, tendo mais de um, as setas aparecem. 
O título é igual ao nome da pessoa. Texto igual a área de texto, imagem destacada tem as instruções e o cargo e empresa tem campos específicos. Também já está ok para a versão mobile. Além disso funciona o touchMove. Só vai aparecer na home, ainda não subi os arquivos da página do produto. Também da para aumentar ou diminuir o tempo de transição dos depoimentos, caso ache necessário.

**Comment by arielrinnert** [comment]
perfeito!

**Comment by arielrinnert** [comment]
cara eu vi aqui q o botão de ir pra trás não ta pegando..

**Comment by amedtler** [comment]
Ajustado.

**Comment by amedtler** [comment]
Outro detalhe. A ordem de exibição deixei pela ordem alfabética do nome.

**Comment by arielrinnert** [comment]
pronto!
