### ISSUE TITLE
Rodapé - Incluir botão de acesso a benefícios mercadológicos

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#30]

**Comment by arielrinnert** [comment]
![desenho rodape](https://cloud.githubusercontent.com/assets/19783148/16391592/37999556-3c7e-11e6-900a-0420afa40eba.jpg)

**Comment by arielrinnert** [comment]
No caso é o link no mapa do site

**Comment by amedtler** [comment]
Agora isso ficou dinâmico, basta ir em aparência/menu. 
Criei dois menus, coluna esquerda e coluna direita. 
Basta selecionar as páginas, reordenar ou criar links manuais. 
É bem simples, qualquer dúvida me pergunta.

**Comment by arielrinnert** [comment]
Ficou top! isso ai!
