### ISSUE TITLE
Criar página Erro 404 personalizada

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#31]

**Comment by amedtler** [comment]
Tem arte ou alguma ideia para essa página?

**Comment by arielrinnert** [comment]
Essa é a ideia .... 
https://projects.invisionapp.com/share/7K712R9DU#/screens/152323835_Layout-OceanDrop-PgTemporaria-V02

**Comment by arielrinnert** [comment]
Os arquivos estão aqui ...
https://drive.google.com/drive/folders/0B4NAYxWygDtlSVZDd3RSOVlSNFE

**Comment by amedtler** [comment]
Implementado.

**Comment by arielrinnert** [comment]
feito
