### ISSUE TITLE
Home - Incluir faixa de fotos de produtos [depois do testimonial] 

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#32]

**Comment by amedtler** [comment]
Esse já tem arte ou está com o Tayron?

**Comment by arielrinnert** [comment]
essa ai a Mar ta dando um grau nas fotos, termina hj ainda, máximo amanhã

**Comment by arielrinnert** [comment]
Arquivo "Home 01" na pasta https://drive.google.com/drive/folders/0B0VHhFX-xi3KWHpMU2p1NkdabTA

**Comment by amedtler** [comment]
Implementado.

**Comment by arielrinnert** [comment]
feito
