### ISSUE TITLE
Produto - Ajustar faixa de compartilhamento [após benefícios]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#35]

**Comment by amedtler** [comment]
Qual é o ajuste?

**Comment by amedtler** [comment]
Esquece, falamos sobre isso ontem. Vai ficar abaixo dos benefícios.

**Comment by arielrinnert** [comment]
esse é o modelo
https://drive.google.com/open?id=0B0VHhFX-xi3KY1hZVjdmeGpNUXc

só q ai só com o facebook e instagram.. a ideia é q compartilhe a página do produto..

**Comment by amedtler** [comment]
Ajustado. 
Obs: Facebook e twitter, correto?

**Comment by arielrinnert** [comment]
ok
