### ISSUE TITLE
Home - Incluir símbolos Nasa e Onu na faixa específica

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#4]

**Comment by arielrinnert** [comment]
![nasa-onu](https://cloud.githubusercontent.com/assets/19783148/16391923/bb33fa5e-3c7f-11e6-8d96-e9a7737f7cdb.jpg)

**Comment by arielrinnert** [comment]
![selonasa1-2](https://cloud.githubusercontent.com/assets/19783148/16391930/c4bd299c-3c7f-11e6-9abf-563e75a3aad1.png)
![selooms2-2](https://cloud.githubusercontent.com/assets/19783148/16391931/c4d40f22-3c7f-11e6-87a4-a6f686060157.png)

**Comment by amedtler** [comment]
Ajustado. 
Obs: Na versão mobile, tirei o background e coloquei uma cor sólida, assim como fiz no rodapé. 
O site já está com muitas imagens, então é preciso otimizar no mobile para não ficar tão pesado, ok?

**Comment by arielrinnert** [comment]
Cara ficou bom, mas acho q da pra reduzir uns 20/30% o tamanho das estampas e ai consequentemente reduzir a altura dessa faixa, senti q ficou alta demais e mal ocupada..

A versão mobile está ok! 100%

**Comment by amedtler** [comment]
Ajustado. Confere lá.

**Comment by arielrinnert** [comment]
top!
