### ISSUE TITLE
Checkout - Quando clicar em PayPal aparecer imagem indicando que o cliente será redirecionado ao site

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#41]

**Comment by amedtler** [comment]
Coloquei um texto. Veja se está bom. Obs: Somente quando clica em "ir para o PayPal"

**Comment by arielrinnert** [comment]
Ta legal assim, mas minha ideia era abrir um campo onde aparece escrito que o cliente será redirecionado ao PayPal.. da mesma forma que quando clica no PagSeguro aparece aquele campo embaixo com os espaços pra informações do cartão de crédito.. é possível? Se for muito complicado mantemos assim agora..

**Comment by amedtler** [comment]
Acho que rola, mas como o paypal agora está como primeira opção esse campo já fica visível, ok? Outra opção é criar um alert. Quando clicar no botão ir para o paypal abre uma caixa de alerta com o aviso e somente dando ok, redireciona para o paypal.

**Comment by arielrinnert** [comment]
saquei, ai acho q já fica mais desagradável pro usuário.. como você colocou já está bom! finalizado!
