### ISSUE TITLE
Checkout - Incluir opção de transferência e depósito apresentando informações básicas

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#42]

**Comment by amedtler** [comment]
Nessa opção você precisa colocar os dados bancário, já habilitei a função no meu ambiente local para testar. Pode inclusive colocar mais de uma conta caso ache interessante. Acesse o painel admin, depois woocommerce > configurações > Aba finalizar compra > opções de pagamento > Depósito, DOC/TED
Pode inclusive modificar o texto que aparece para o usuário. Não esqueça de adicionar a conta.

**Comment by arielrinnert** [comment]
feito
