### ISSUE TITLE
Home - Trocar Banner 3 por Banner de benefícios

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#43]

**Comment by amedtler** [comment]
Pode me mandar a imagem?

**Comment by arielrinnert** [comment]
O Tayron vai desenvolver esta imagem

**Comment by amedtler** [comment]
Isso ficou pronto?

**Comment by arielrinnert** [comment]
ainda não

**Comment by arielrinnert** [comment]
Aqui está o Banner 3: https://drive.google.com/drive/folders/0B0VHhFX-xi3KNEdGZmY1ckUyRnc

**Comment by arielrinnert** [comment]
Aqui abaixo vou listar o que deve aparecer na faixa "Benefícios"

1º - Título: SUPERFOODS
Subtítulo: Alimentos completos para seu dia a dia.
Texto: Proteína, aminoácidos, vitaminas, minerais, antioxidantes e óleos essenciais para enriquecer a sua dieta e simplificar a sua nutrição mesmo diante de uma rotina intensa de atividades.
Imagem: imagem atual do 2º item ("Health")

2º - Título: PERFORMANCE
Subtítulo: Energia e recuperação para o seu corpo.
Texto: Superfoods ideais para você manter o corpo ativo, saudável e protegido na busca pelos melhores resultados na sua prática de atividade física. 
Imagem: https://pixabay.com/pt/nadadores-nata%C3%A7%C3%A3o-corrida-79592/

3º - Título: NATURAL FOOD
Subtítulo: Complemente a sua dieta naturalmente.
Texto: Superfoods 100% vegetais que fornecem de maneira prática e sustentável os nutrientes essenciais para o bom funcionamento do seu corpo e mente. Assim como você, não aceitamos produtos testados em animais.
Imagem: imagem atual do 1º item ("Nutrition")

**Comment by arielrinnert** [comment]
Assim fica a imagem do item 2 "PERFORMANCE"

https://drive.google.com/open?id=0B0VHhFX-xi3KTHM3RnBpZlFfRlU

**Comment by amedtler** [comment]
Quanto a faixa benefícios. Veja se é isso? 
Obs: Ainda não subi para o servidor, mas está pronto. 
![beneficios](https://cloud.githubusercontent.com/assets/734230/17125155/740c0f78-52c7-11e6-8b3e-2b93358a7f08.png)

**Comment by amedtler** [comment]
Sobre o arquivo do banner 3. É pra trocar os 3 banners do arquivo e utilizar o formato do texto conforme a arte? Também já deixei pronto aqui, falta apenas o texto na qual não tenho certeza.

**Comment by arielrinnert** [comment]
Sobre os benefícios: esta certo

Sobre o texto dos banners pode deixar igual o Tayron fez... ai tem q trocar tudo..

**Comment by amedtler** [comment]
Ta no ar. Confere os benefícios e os banners.

**Comment by arielrinnert** [comment]
feito
