### ISSUE TITLE
Home - Incluir faixa de subscribe [antes do rodapé]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#44]

**Comment by arielrinnert** [comment]
Conforme comentamos:
- faixa de fundo branco
- Título: "Mantenha seu conhecimento sempre a frente"
- Subtítulo: "Receba novidades, curiosidades, receitas, promoções e descontos todo mês!"
- Caixa de inscrição: Borda colorida básica
- Call to action: "Cadastrar"

**Comment by amedtler** [comment]
Da uma olhada se ta bom ou assim ou se tem outra ideia. 
![captura de tela 2016-06-29 as 16 54 12](https://cloud.githubusercontent.com/assets/734230/16466661/5512ae5e-3e1a-11e6-8161-9be93ab6ad3d.png)

**Comment by amedtler** [comment]
Implementado.

**Comment by arielrinnert** [comment]
Ficou da hora.. só que o botão do "Cadastre-se" ta sobrepondo o menu do site, tanto no PC quanto no celular..

**Comment by amedtler** [comment]
Verdade. Acabei de ajustar. É só atualizar a página para ver.

**Comment by arielrinnert** [comment]
fechou!
