### ISSUE TITLE
Produto - Incluir faixa de inf. adicional (sem medicamento +  não p/ gravida + pode sentir mau estar) [Abaixo das formas de pagamento]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#46]

**Comment by amedtler** [comment]
naquela faixa com as informações adicionais: sem interação com medicamentos, não recomendado para gestantes…. tem um texto de marcação abaixo do título. Vai ter algum texto ou somente o título, assim como está no psd home_final?

**Comment by arielrinnert** [comment]
Só pra constar, essa faixa dessa atividade aqui fica abaixo dessa (https://github.com/amedtler/oceandrop/issues/47), compartilham o mesmo título inclusive..

**Comment by arielrinnert** [comment]
Sem interação com medicamentos: Nossos superfoods são alimentos! Não são fórmulas de compostos isolados ou de ervas medicinais e não tem qualquer interação com medicamentos.

Não p/ grávidas: Grávidas, nutrizes (mães que amamentam) e nutrizes devem evitar o consumo deste produto sem acompanhamento profissional. O apoio de um nutricionista é sempre ideal!

Não p/ alérgicos: Assim como outros alimentos de origem ligada ao mar, como peixes e crustáceos, as microalgas podem causar reações alérgicas. Qualquer dúvida consulte um profissional.

**Comment by amedtler** [comment]
Ajustado

**Comment by arielrinnert** [comment]
ok
