### ISSUE TITLE
Produto - Incluir faixa de apoio ao consumo [abaixo do testimonial]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#47]

**Comment by arielrinnert** [comment]
Imagens em:
https://drive.google.com/drive/folders/0B0VHhFX-xi3KMmZGVXZuWUFWRWs

**Comment by arielrinnert** [comment]
Só pra registrar, essa faixa aqui de apoio ao consumo fica acima desta: https://github.com/amedtler/oceandrop/issues/46

alias, compartilham o mesmo título..

**Comment by arielrinnert** [comment]
SPIRULINA:
Simples: SIMPLICIDADE E RESULTADO
A praticidade que você esperava para manter-se energizado e focado.
É fácil, apenas duas cápsulas, 30 minutos antes das suas duas principais refeições. 
Lembre-se, o consumo regular acompanhado de um copo de água otimiza os seus resultados!

Avançado: CRIATIVIDADE PARA IR ALÉM
Que tal enriquecer nutricionalmente suas bebidas e alimentos incluindo spirulina em suas receitas? Você pode abrir as cápsulas e deixar a imaginação fluir!
**Foco no desempenho!** Consuma spirulina pré e pós atividade física para energizar e recuperar seu corpo naturalmente.
**Evite lanches desnecessários** e excessos na alimentação consumindo spirulina nos horários de maior apetite ou entre as refeições.

**Comment by arielrinnert** [comment]
CHLORELLA:
Simples: SIMPLICIDADE E RESULTADO
Ficou prático cuidar do seu corpo, basta ingerir uma cápsula em cada período do dia (manhã, tarde e noite), preferencialmente trinta minutos antes de suas refeições.
Lembre-se, o consumo regular acompanhado de um copo de água otimiza os seus resultados!

Avançado: CRIATIVIDADE PARA IR ALÉM
Dê um toque especial em suas receitas. Você pode abrir as cápsulas de chlorella e enriquecer suas bebidas e alimentos com criatividade!
**Recupere seus músculos e tecidos** ingerindo chlorella após a sua atividade física.
**Faça uma limpeza profunda** reservando uma dose diária para ser ingerida antes de dormir.
**Diminua os efeitos do álcool** e má alimentação com um drop de chlorella antes e depois de sua diversão.

**Comment by arielrinnert** [comment]
Apoio Simples
![uso-simples](https://cloud.githubusercontent.com/assets/19783148/16537667/66981f94-3fdf-11e6-86c1-75fc389a5ddc.png)

**Comment by arielrinnert** [comment]
Apoio Avançado
![uso-avancado](https://cloud.githubusercontent.com/assets/19783148/16537670/73badedc-3fdf-11e6-86a5-29e74882f3b7.png)

**Comment by arielrinnert** [comment]
Essa última foto vai repetir a q está na Home Page.. então já peço pra vc alterar a imagem da Home pra essa:
![home](https://cloud.githubusercontent.com/assets/19783148/16537679/97f19e76-3fdf-11e6-818a-a05dce8c2b24.png)

**Comment by amedtler** [comment]
Blz. Tudo ajustado. Lembrando que esse texto pode ser modificado em cada produto. Criei os campos dinâmicos. Título apoio ao consumo. Ah! Uma coisa que já queria ter te avisado. Essas imagens que tu envia sem fundo, não consigo aproveitar nenhuma, não sei como está fazendo, mas fica serrilhado.

**Comment by amedtler** [comment]
Ah!! Power box não coloquei esse texto, pois não sabia como tinha que ficar, qualquer coisa é só entrar no produto e ajustar.

**Comment by arielrinnert** [comment]
dai ta certinho, só te peço pra colocar a foto da loira ali tomando um suco na Home Page, no lugar da foto q repete ai..

**Comment by amedtler** [comment]
Já troquei isso, atualiza a página para ver.

**Comment by arielrinnert** [comment]
feito
