### ISSUE TITLE
Produto - Incluir faixa de vantagens mercadológicas (Entrega todo Brasil + 30-d garantia + 3x sem juros) [antes de apresentar outros produtos]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#5]

**Comment by arielrinnert** [comment]
Colocar depois da faixa de mídias sociais

**Comment by arielrinnert** [comment]
[Vantagens mercadológicas - Página produtos.docx](https://github.com/amedtler/oceandrop/files/335622/Vantagens.mercadologicas.-.Pagina.produtos.docx)

**Comment by arielrinnert** [comment]
![selossitefinal16](https://cloud.githubusercontent.com/assets/19783148/16391898/97bff320-3c7f-11e6-82ce-281ff330d0ae.png)
![sellosfinales-16](https://cloud.githubusercontent.com/assets/19783148/16391899/97d8ac26-3c7f-11e6-9ccc-e9afea38e3e5.png)
![selossitefinal2](https://cloud.githubusercontent.com/assets/19783148/16391900/97f7815a-3c7f-11e6-8f89-929f5ea8d743.png)

**Comment by arielrinnert** [comment]
Só uma alteração, no texto dos 30 dias de garantia, colocar assim: "Você vai amar nossos produtos! Aqui você tem trinta dias de garantia de satisfação na primeira compra! Abriu o produto? Ganhe créditos na loja! Se arrependeu da compra? Receba seu dinheiro de volta!"

**Comment by arielrinnert** [comment]
Será necessário atualizar também o texto das páginas de políticas de trocas e devoluções:

(Forma de Reembolso / Restituição dos valores pagos) substituir por:
"Pagamentos pelo PagSeguro ou PayPal:
A Ocean Drop notificará o Pagseguro ou PayPal para que o mesmo faça o estorno do pagamento do cliente:
1-  Caso tenha sido pago com boleto do PagSeguro, após estorno,  o crédito ficará disponível de imediato no pagseguro para que o cliente solicite a tranferência do valor do pagseguro para sua conta corrente.
2-  Caso tenha sido pago com cartão de crédito pelo PagSeguro ou PayPal, o estorno ocorrerá em até 02 (duas) faturas subsequentes. Este procedimento é de responsabilidade do pagseguro e da da administradora do cartão utilizado.

Pagamentos não intermediado – Depósito, Transferência:
O reembolso será feito na conta corrente indicada pelo Cliente no prazo de até 10 dias úteis contados do recebimento pela Ocean Drop do produto. É necessário que o CPF do titular seja o mesmo que consta no pedido (CPF do cliente). Não será concedido crédito a terceiros."

Incluir depois das (Formas de envio):
"Condição especial da primeira compra (30 dias de garantia de satisfação)

Devolução por Insatisfação

Na primeira compra pelo e-commerce, o Cliente poderá solicitar a devolução do produto adquirido no prazo de até 30 (trinta) dias corridos contados do recebimento do respectivo produto e ser reembolsado de todos os valores pagos ou ter crédito gerado para compra de outros produtos no E-commerce referente aos valores pagos pelo produto.
Neste caso, o cliente deverá entrar em contato com o Serviço de Atendimento ao Cliente (SAC) através do e-mail falecom@oceandrop.com.br ou pelo telefone +55 (47) 9635-2000, e seguindo as instruções que lhe forem passadas.
Se o Cliente exercer seu direito de Devolução por Insatisfação em estrita conformidade com os termos previstos neste item:
1-  Será ressarcido pela Ocean Drop com todos os valores por ele pagos pelo(s) produto(s) conforme descrito anteriormente no item (Forma de Reembolso/ Restituição dos valores pagos), quando a Ocean Drop receber o produto lacrado;
2-  Ou será creditado pela Ocean Drop com todos os valores por ele pagos pelo(s) produto(s) para comprar outro(s) produto(s) de valor equivalente no e-commerce da Ocean Drop, quando a Ocean Drop receber o produto sem lacre ou com o lacre aberto.
O valor do frete de envio do produto do Cliente para a Ocean Drop e, quando pertinente, o envio do produto da Ocean Drop para o Cliente, será pago pelo cliente. Para isso, o Cliente deve entrar em contato com a Ocean Drop por e-mail falecom@oceandrop.com.br.
Para que estas condições tenham validade é necessário o envio da embalagem original. 
Não será concedido crédito a terceiros."

(Arquivo completo)
[Políticas E-commerce.docx](https://github.com/amedtler/oceandrop/files/335890/Politicas.E-commerce.docx)

**Comment by amedtler** [comment]
Acho que esse texto é mais fácil você mesmo trocar, pois estou com medo de apagar alguma informação importante. Além disso, não tenho word aqui instalado, uso apenas o drive e lá o arquivo ficou quebrado.

**Comment by arielrinnert** [comment]
blz eu passo pro word o texto depois passo p fazer o upload dele completo.
