### ISSUE TITLE
Rodapé - Remover subscribe do rodapé

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#50]

**Comment by amedtler** [comment]
Tem várias modificações no rodapé, acho que seria interessante a Mar montar a versão final com todos os ajustes, assim facilita o trabalho e aprovação. O que acha?

**Comment by arielrinnert** [comment]
Assim, antes de remover o subscribe temos que criar uma faixa para o subscribe antes do rodapé.. eu quero tirar ele de lá mas não da pra deixar a página sem ele..

E sobre os ajustes gerais, vamos fazer isso sim, até acho que o plano de fundo ali como está é tranquilo, a questão seria redistribuir os elementos né? E ai já arrumamos ele conforme você comentou, frente aos erros verificados, correto?

**Comment by amedtler** [comment]
Exato. Também acho que precisa aparecer em algum lugar, por isso achei melhor não remover ainda.

**Comment by arielrinnert** [comment]
![desenho rodape](https://cloud.githubusercontent.com/assets/19783148/16391573/271857e4-3c7e-11e6-933b-6ba54b034e9e.jpg)

**Comment by amedtler** [comment]
Removido.

**Comment by arielrinnert** [comment]
finalizado
