### ISSUE TITLE
Home - Incluir faixa de social media [depois do blog]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#51]

**Comment by arielrinnert** [comment]
Imagens em:
https://drive.google.com/drive/folders/0B0VHhFX-xi3KMmZGVXZuWUFWRWs

**Comment by amedtler** [comment]
Qual o link do youtube?

**Comment by amedtler** [comment]
Feito, só faltou o link do youtube.

**Comment by arielrinnert** [comment]
Segue o link do youtube
https://www.youtube.com/channel/UCIc7xzKea9394vWmVht1amA

**Comment by amedtler** [comment]
Blz. Ajustado.

**Comment by arielrinnert** [comment]
feito!
