### ISSUE TITLE
Rodapé - Incluir menu de mapa do site

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#55]

**Comment by arielrinnert** [comment]
![desenho rodape](https://cloud.githubusercontent.com/assets/19783148/16391546/09315942-3c7e-11e6-9442-459150717aaa.jpg)

**Comment by amedtler** [comment]
Implementado. 
No painel admin acesse aparência/menu.

**Comment by arielrinnert** [comment]
finalizado
