### ISSUE TITLE
Produto - Incluir faixa de fotos de produtos [antes dos benefícios]

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#6]

**Comment by arielrinnert** [comment]
Essa faixa aqui na real pode ficar posicionada antes do "Subscribe"

**Comment by arielrinnert** [comment]
Fotos estão nessa pasta:  https://drive.google.com/drive/folders/0B0VHhFX-xi3KWHpMU2p1NkdabTA
- Página da Spirulina = "Spirulina 03"
- Página da Chlorella = "Chlorella 03"
- Página da PowerBox = "Power Box 03"

**Comment by arielrinnert** [comment]
feito
