### ISSUE TITLE
Home - Integração API Instagram

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#64]
Fazer integração e customizar conforme layout. 
Obs: Essa tarefa não estava incluída no orçamento do primeiro pacote.

**Comment by amedtler** [comment]
O instagram mudou a API deles no dia 1 de junho, enfim, ficou um pouco mais complexo pra fazer essa integração. Vou ter que pesquisar um pouco mais. Coloquei aquelas imagens do psd como base, depois que integrar "puxa" automático.

**Comment by arielrinnert** [comment]
Legal eu vi ali.. assim q estiver integrado eu fecho a tarefa

**Comment by amedtler** [comment]
Estava lendo sobre isso, agora é preciso estar logado na conta e fazer a autorização do acesso. Sendo assim, vou precisar dos dados de acesso dessa conta no instagram para fazer isso.

**Comment by arielrinnert** [comment]
user: oceandrop
passw: spirulinaechlorella

**Comment by amedtler** [comment]
Estava lendo a respeito das modificações da API. Agora não é mais possível buscar por uma hashtag global e exibir as imagens em qualquer lugar. É possível exibir somente a hashtag do usuário autenticado. Ou seja, só será possível exibir do usuário oceandrop. Além disso, o tamanho padrão das imagens agora é diferente, a altura e flexível. Enfim, veja um exemplo de como ficaria no site. Só estou mostrando pra ver se é isso mesmo que querem. É claro que posso diminuir um pouco o tamanho da imagem por css, mas o ajuste vale para todas, ou seja, algumas iriam cortar, da forma que está, está mostrando a altura completa. 
![captura de tela 2016-07-05 as 17 18 39](https://cloud.githubusercontent.com/assets/734230/16598556/f48af914-42d4-11e6-84ee-ddf357988f2e.png)

**Comment by arielrinnert** [comment]
entendi Andreson, nesse formato ai não fica legal não ahhahahaha

cara a ideia que eu tive é: 
- manter o formato que esta agora no site
- deixar uma opção no painel de controle pra alterarmos a imagem (ou as imagens) quando quisermos..

rola?

**Comment by arielrinnert** [comment]
precisa de ajuda ainda pra tocar esse?

**Comment by arielrinnert** [comment]
@amedtler previsão pra entregar?

**Comment by amedtler** [comment]
Assim que concluir as atividades com mais prioridade.

**Comment by amedtler** [comment]
Implementado. 
Está no menu a esquerda "instagram". 
O tamanho da imagem deve ser 300x300px (coloquei esse aviso quando for adicionar um item), 
alem disso, a ordem de exibição pode ser modificada, basta visualizar todos e arrastar para cima ou para baixo. 
A exibição é de 6 imagens na versão desktop e 3 imagens na versão mobile (apenas repete).
