### ISSUE TITLE
Home - Padronizar exibição dos produtos

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#65]
Ariel, veja se é isso. Deixei a exibição da power box igual dos produtos acima. Não subi o arquivo para o servidor, mas está pronto, assim que me der ok subo lá. Além disso, coloquei aquele lance de reordenar a exibição dos produtos, nesse caso vai ter como escolher a ordem. 

Veja o anexo se é isso. Aguardo confirmação para subir o arquivo. 
Obs: A parte abaixo (powerbox) retirei. 

![produtos-oceandrop](https://cloud.githubusercontent.com/assets/734230/17123921/b308c928-52bd-11e6-9699-db6f4b218972.jpg)

**Comment by arielrinnert** [comment]
vc consegue colocar duplicar o título entre as faixas e colocar uma cor um pouquinho mais escura (não branca) do que a faixa dos produtos individuais?

**Comment by amedtler** [comment]
Ta no ar.

**Comment by arielrinnert** [comment]
Segue o modelo pra implementar:
https://drive.google.com/drive/folders/0B0VHhFX-xi3KaVVGQ3I5ZjRGQTA

**Comment by amedtler** [comment]
Massa, estou fazendo. Já prepara as imagens dos produtos com esse formato quadrado, pois atualmente elas tem uma borda na própria imagem.

**Comment by amedtler** [comment]
Ta pronto aqui, mas acho melhor tu me mandar todas as imagens, pois subo tudo junto. 
Tenta manter um padrão de tamanho. O modelo que estou usando é 414x414px. 
Mas se quiser fazer um padrão diferente por categoria, não tem problema, desde que a largura seja 414px. Vai ficar bem massa. Ahh! Além disso, achei que a exibição de 3 colunas ficou melhor do que 4. Mas depois que mandar as imagens tiro um print e te mostro como fica com 3 e com 4.

**Comment by arielrinnert** [comment]
massa! eu coloquei as fotos ali na mesma pasta do drive! https://drive.google.com/drive/folders/0B0VHhFX-xi3KaVVGQ3I5ZjRGQTA

**Comment by amedtler** [comment]
Ah! Outra dúvida. No botão adicionar no carrinho, tu quer que apenas adicione e continue navegando na mesma página ou que já vá para o carrinho?

**Comment by arielrinnert** [comment]
É pra ele ficar na mesma página, e ai acrescenta uma unidade ao carrinho, aparecendo no contador (q ainda não ta no ar mas vai estar no futuro)

**Comment by amedtler** [comment]
Como agora temos a informação da quantidade de cápsulas, preciso que me informe a quantidade de cada produto. Isso é dinâmico, mas já vou deixar pronto.

**Comment by arielrinnert** [comment]
então todos os produtos tem 240 capsulas cada unidade... ai só os produtos de R$ 37 reais é q tem 60 unidades..  acho q é bom colocar um "por unidade" ou "/ unidade" depois de informar a quantidade de cápsulas..

**Comment by amedtler** [comment]
Tá no ar. Confere assim que der para ver se está ok. 
Obs1: Na página de edição do produto, criei os campos dinâmicos para a nova exibição da home, caso queira mudar alguma informação é só procurar na coluna Produto - Informações Adicionais. 
Obs2: Hoje vou trabalhar até as 7h da manhã, então na parte da manhã vou estar ausente, caso tenha algo urgente, pode me ligar. 48.9102-4148

**Comment by arielrinnert** [comment]
Ficou muito da hora! Só gostariamos de ver como ficaria com 2 produtos por linha apenas (assim todas as faixas ficariam 2x2).. e a fonte pequena está muito pequena, se vc puder aumentar um pouco só..

ai lá na outra atividade agente ajusta a função do "hover" e etc..

**Comment by amedtler** [comment]
Ajustado. Produtos em 2 colunas e fonte aumentada no limite. Gostei assim.

**Comment by arielrinnert** [comment]
bem da hora! só reduz uns 15/20 % o tamanho do quadro por favor..

**Comment by amedtler** [comment]
Reduzi mais um pouco. Se achar que precisa reduzir mais, terei que diminui um pouco o tamanho da fonte com o nome do produto.

**Comment by arielrinnert** [comment]
feito!
