### ISSUE TITLE
Menu - remover efeito deslizar do botão contato

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#66]

**Comment by amedtler** [comment]
Ajustei a âncora, mas mantive o efeito. A estrutura criada para fazer esse efeito é bem complexa, preciso mexer em outras coisas para tirar isso. Vou deixar para depois.

**Comment by arielrinnert** [comment]
cara está bom daquele jeito a principio, qualquer coisa arrumamos se ficar meio ruim
