### ISSUE TITLE
Site e Blog - Parametrizar links 

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#67]
Ok. É só enviar a lista.

**Comment by arielrinnert** [comment]
cara na real agente não tem certeza de que links todos que tem no site que precisamos parametrizar.. você sabe onde encontro listado os links que tem no site?

**Comment by amedtler** [comment]
Acho que to fazendo confusão, pode me explicar exatamente qual a ideia?

**Comment by amedtler** [comment]
Esse item estou vendo com o Michael, estamos fazendo testes.

**Comment by amedtler** [comment]
Empresa responsável está analisando.

**Comment by roelsmich** [comment]
@amedtler so para que não tenha confusão, é para você fazer mesmo. Outra empresa não entra nisso.

**Comment by roelsmich** [comment]
boa tarde @amedtler, conseguiu avançar?

**Comment by amedtler** [comment]
Sim, acho que vai dar certo. Estou monitorando os testes.

**Comment by amedtler** [comment]
Fiz novos testes. Estou monitorando para ver se vai dar certo.

**Comment by amedtler** [comment]
@roelsmich, acho que agora deu certo. 
Acessa o analytics, vai em relatórios, comportamento, eventos. 
![captura de tela 2016-11-02 as 21 39 34](https://cloud.githubusercontent.com/assets/734230/19951401/eacd64c4-a144-11e6-98ef-d80859a154ce.png)

**Comment by roelsmich** [comment]
Boa tarde @amedtler, dei uma olhada aqui. 
So para ter certeza: você recebeu o convite para a nova conta de analytics do Ocean Drop que usamos agora né? Anexei uma imagem com o numero da propriedade 
![schermafbeelding 2016-11-07 om 16 45 35](https://cloud.githubusercontent.com/assets/22944469/20071000/d671f92c-a509-11e6-83cb-a7a5d9da5e06.png)

Você também pode me explicar então qual evento corresponde a qual botão? 
P.e. o Newsletter corresponde ao evento quando uma pessoa deixa o lead na caixa do newletter? 
O evento "home" corresponde ao que? O logo no cabeçalho? 

E para ver então as pessoas que chegaram no site atraves dos botões do blog: como consigo ver isso? Eu seleciono a opção  "origem/midia" na dimensão secundaria? 

Talvez pode ser mais facil a gente fazer um  skype de 10min para esclarecer em vez de ficar digitando tudo isso aqui.

**Comment by amedtler** [comment]
Então, agora vamos ter que inserir esses dados manualmente. 
Criar o evento para cada botão.
Podemos combinar de falar na quarta-feira, pode ser? 
Estou disponível após às 18h. Só me avisa.

**Comment by roelsmich** [comment]
skype quarta-feira  as 18h30 então?

**Comment by roelsmich** [comment]
segue o documento (coloquei em ZIP pq o git não suporte RTF)

[Links Paramentrizados Botões Site e Blog.zip](https://github.com/amedtler/oceandrop/files/583204/Links.Paramentrizados.Botoes.Site.e.Blog.zip)

**Comment by amedtler** [comment]
Está feito. 
Assim como tinha comentado no início dessa tarefa, algumas tags não podem ser colocadas pois o conteúdo é dinâmico. 
O que ficou de fora foi o clique na imagem, conheça mais e adicionar ao carrinho de todos os produtos da home do site e as categorias da home do blog.

**Comment by roelsmich** [comment]
você testou? Eu fiquei buscando no analytics do blog e do site também mas ele não mostra cliques registrados através dos links.. @amedtler

**Comment by amedtler** [comment]
Sim, tinha testado. Vou verificar novamente amanhã.

**Comment by amedtler** [comment]
Michael, pelo que verifiquei está tudo certo. 
Só não sei te explicar muito bem como é feito a leitura no analytics, realmente não manjo nada, mas as informações estão indo.
