### ISSUE TITLE
Home - exibir produtos por categoria

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#68]
Ta feito. Observa na lista de produtos que criei 3 categorias. 
- simples 
- boxes
- acessorios
  Quando criar um novo produto precisa selecionar a categoria correspondente para exibir o produto corretamente. 
  Quando publicar o primeiro produto da categoria acessórios, vai aparecer a faixa. 
  Obs: Também diminui o espaço abaixo do produto, conforme solicitou.

**Comment by arielrinnert** [comment]
feito
