### ISSUE TITLE
Carrinho e checkout - Definir limite mínimo de compras, 36 reais

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#70]
Ta feito. 
Já coloquei no ar. 
Aparece a seguinte mensagem: (ignora o valor do produto, foi um teste que fiz no ambiente local)
![captura de tela 2016-07-28 as 23 35 26](https://cloud.githubusercontent.com/assets/734230/17236111/fa60a500-551c-11e6-8b25-b4e6f6310370.png)

**Comment by arielrinnert** [comment]
feito
