### ISSUE TITLE
Produto - Vantagens mercadologicas depois dos benefícios

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#71]
Colocar “Vantagens mercadologicas” depois dos benefícios (e fazer a barra de compra rolar até lá)

Ajustado.

**Comment by arielrinnert** [comment]
cara na real a barra de compra não pode rolar até lá pq tampa o conteúdo.. ela pode apagar antes..

e ali no texto só muda o das 3x pra isso: "Temos as melhores condições para você! Parcele tudo em até 3X sem juros! Faremos o que for possível para que você possa ter seus superfoods!"

**Comment by amedtler** [comment]
Ajustado

**Comment by arielrinnert** [comment]
Boa! pode diminuir uns 15% o tamanho dos selos pfv?

**Comment by amedtler** [comment]
Ajustado. Aguardando aprovação.

**Comment by arielrinnert** [comment]
cara não sei se só o do meio diminuiu, mas ele ficou melhor q os outros.. pode padronizar tudo pfv?

**Comment by amedtler** [comment]
Tinha reduzido todos, mas o tamanho é diferente. Ajustei novamente.

**Comment by arielrinnert** [comment]
feito
