### ISSUE TITLE
Carrinho e Checkout - Informar prazo para entrega

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#72]
Pode confirmar a mensagem e prazo que deve aparecer?

**Comment by arielrinnert** [comment]
[ao lado do valor do PAC] - prazo médio de entrega de 10 dias.
[ao lado do valor do SEDEX] - prazo médio de entrega de 4 dias.

**Comment by amedtler** [comment]
Implementado

**Comment by arielrinnert** [comment]
cara pode aumentar um pouquinho o tamanho só...

**Comment by amedtler** [comment]
Ajustado. Aguardando aprovação.

**Comment by arielrinnert** [comment]
então só vi no carrinho, no checkout não.. pode por na barra "Seu pedido" por favor?

valeu..

**Comment by amedtler** [comment]
Aparece sim, porém se o cliente não calcula o frete na página do carrinho essa informação não aparece, somente depois de confirmar o cep.

**Comment by arielrinnert** [comment]
feito
