### ISSUE TITLE
Produto - Alterar textos e funções do box fixo (comprar)

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#73]
Na barra de compra (a direita, fixo) alterar o botão, segmentando em dois: o primeiro com “Adicionar ao carrinho”; e o segundo com “Finalizar compra” VERSÃO 03

**Comment by amedtler** [comment]
Feito, veja se é isso.

**Comment by arielrinnert** [comment]
![image](https://cloud.githubusercontent.com/assets/19783148/17388684/1efe03ec-59d4-11e6-8134-059646e3a111.png)

**Comment by arielrinnert** [comment]
na real é tipo eu coloquei acima.. assim o usuário não depende de adicionar ao carrinho pra poder finalizar a compra..

**Comment by amedtler** [comment]
Ajustado. Veja se é isso.

**Comment by arielrinnert** [comment]
cara pode eliminar o botão do quero presentear, e puxar um pouco pra cima a posição base, porque aqui não está aparecendo o final da barra de compra... assim ó:

![image](https://cloud.githubusercontent.com/assets/19783148/17756118/57eeb094-64b4-11e6-95d9-ca7372f84845.png)

**Comment by amedtler** [comment]
ajustado

**Comment by arielrinnert** [comment]
feito
