### ISSUE TITLE
Menu - Transformar carrinho em um ícone no menu VERSÃO 2

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#74]
Esse preciso da arte. Conversei com a Mar, ela disse que está trabalhando novamente com vocês. Acho mais fácil tu explicar o que quer pra ela e ela me envia, ou coloca o arquivo aqui mesmo, assim facilita.

**Comment by arielrinnert** [comment]
Fica assim:

![image](https://cloud.githubusercontent.com/assets/19783148/17388795/d7ef048c-59d4-11e6-9c94-5c02a6de1110.png)

as imagens estão aqui: https://drive.google.com/drive/folders/0B4NAYxWygDtlSVZDd3RSOVlSNFE

**Comment by amedtler** [comment]
Implementado.

**Comment by arielrinnert** [comment]
feito
