### ISSUE TITLE
Menu - Apresentar contador de produtos no carrinho do menu VERSÃO 2

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#75]
Precisa arte.

**Comment by arielrinnert** [comment]
Fica assim:

![image](https://cloud.githubusercontent.com/assets/19783148/17388808/f762d03c-59d4-11e6-8cc0-f74d693b93bb.png)

as imagens estão aqui: https://drive.google.com/drive/folders/0B4NAYxWygDtlSVZDd3RSOVlSNFE

**Comment by amedtler** [comment]
Implementado. Obs: Coloquei o ícone do carrinho que já havia na lista de ícones inserida no site. Ok? Dessa forma a qualidade fica melhor.

**Comment by arielrinnert** [comment]
feito
