### ISSUE TITLE
Produto - Ajustar altura da primeira foto larga da página de produtos (para caber a segunda foto do carrocel)

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#79]
Esse item não entendi. Pode me explicar? Está como prioridade 10 da planilha.

**Comment by arielrinnert** [comment]
então basicamente é pra ajustar a altura da faixa, ou algum outro ajuste que faça a segunda foto do carrocel aparecer inteira..

olha só na página https://oceandrop.com.br/produto/spirulina/ como q fica a segunda foto da primeira faixa..

**Comment by amedtler** [comment]
Ajustado. Aguardando aprovação.

**Comment by arielrinnert** [comment]
feito
