### ISSUE TITLE
Carrinho - Aumentar largura do espaço pra inserir o cupom no Carrinho

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#80]
Ajustado

**Comment by arielrinnert** [comment]
legal, só q o botão ficou pra baixo.. bom é ele aparecer na mesma linha..

**Comment by arielrinnert** [comment]
Ficou assim..

![image](https://cloud.githubusercontent.com/assets/19783148/17388953/403782fc-59d6-11e6-88ab-a28491676114.png)

**Comment by amedtler** [comment]
Ajustado! Aguardando aprovação.

**Comment by arielrinnert** [comment]
legal!
