### ISSUE TITLE
Criar página FAQ

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#81]

**Comment by amedtler** [comment]
Implementado. No painel tem a opção FAQ, basta cadastrar os itens. 
O título é a pergunta e o conteúdo do texto é a resposta. Coloquei duas de marcação só pra ti ver. 
Quando clicar em ver todas, poderá arrastar para cima ou para baixo para mudar a ordem de exibição. 
A página é essa: https://oceandrop.com.br/faq/ 
Já está disponível, porém não tem link em lugar algum, depois que cadastrar as perguntas é só adicionar ao menu do mapa do site (me avisa que faço isso). 
Dá uma olhada, qualquer coisa me avisa.

**Comment by arielrinnert** [comment]
cara da hora! isso ai! agente mesmo consegue jogar as perguntas e eu crio o link lá no mapa do site pode deixar.. depois qualquer coisa eu te passo uns botões q agente pode acabar colocando no site..

só ia te falar pra mudar o título FAQ para PERGUNTAS FREQUENTES e o subtítulo pode tirar.. e ai pra aproximar um pouco a tabela do título..

uma dúvida, da pra colocar imagem no conteúdo da resposta?

**Comment by amedtler** [comment]
Ajustado. Sim, pode colocar imagens. 
Novo link: https://oceandrop.com.br/perguntas-frequentes/

**Comment by arielrinnert** [comment]
top! feito
