### ISSUE TITLE
Geral - Inclusão área do cliente

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#82]

**Comment by amedtler** [comment]
Implementado. Coloquei o botão minha conta no rodapé, onde o cliente consegue ver os últimos pedidos, alterar/editar dados pessoais, etc... Talvez seria interessante colocar esse botão em algum lugar mais destacado (menu principal), pois se a pessoa logar, ao chegar no checkout as informações já aparecem preenchidas, caso contrário a pessoa terá que preencher todas as informações.

**Comment by arielrinnert** [comment]
irado, isso ai! é importante lembrar de deixar ativado a inclusão da senha do cliente lá na compra agora.. e ai no caso só da pra comprar se fizer cadastro ou se já tiver e estiver logado né?

quanto ao botão visível, você pode colocar este abaixo no menu, na ponta esquerda?
![user](https://cloud.githubusercontent.com/assets/19783148/17784110/9cc80808-6551-11e6-8067-b8b48482789c.png)

**Comment by amedtler** [comment]
Não acha que ficaria melhor assim? 
Qualquer coisa, faz um esboço pra mim, lembrando que tem o outro formato de menu quando rola a tela. 
![menu-v1](https://cloud.githubusercontent.com/assets/734230/17785024/6d57ad22-6555-11e6-95ef-7c93137ec24e.jpg)

**Comment by amedtler** [comment]
Ah! Já ativei a função. Agora só compra com cadastro na loja.

**Comment by arielrinnert** [comment]
então, bem isso na real, ta ótimo, pode tocar!

**Comment by amedtler** [comment]
Ajustado. 
Obs: Tive que reduzir um pouco o espaçamento, caso contrário teria que diminuir a fonte. 
Além disso, também tive que trocar o ícone do blog, pois o padrão utilizado é svg e aquele que tinha colocado não era e de fato não tinha ficado muito bom. Procurei um que é praticamente igual.

**Comment by arielrinnert** [comment]
top!
