### ISSUE TITLE
Inserir código Teste A/B 

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#83]
Código inserido.

**Comment by amedtler** [comment]
Deu certo?

**Comment by arielrinnert** [comment]
cara eu não recebi mais respostas da Catarinas.. vc sabe onde eu consigo ver os resultados?

**Comment by amedtler** [comment]
Pior que não sei. Na verdade não sei qual a ferramenta que está sendo utilizada.

**Comment by arielrinnert** [comment]
ta tranquilo, vou falar com a Priscilla de novo, senão chega dessa catarinas ai..
