### ISSUE TITLE
Site - Avaliação pagespeed 

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#87]
Fiz a análise. Não está dos piores (está na média), mas dá pra melhorar bastante. 
Segue resultado: 
![captura de tela 2016-08-18 as 02 38 37](https://cloud.githubusercontent.com/assets/734230/17763164/3e07ba20-64ed-11e6-974c-a82131e11467.png)

**Comment by amedtler** [comment]
Fiz alguns ajustes, mas vou esperar até domingo para te dar um retorno sobre isso, pois pode ter algum cache no servidor. Quando tiver valendo os ajustes que fiz te aviso para ver se teve alguma melhora significativa.

**Comment by roelsmich** [comment]
@amedtler  pode usar essa ferramenta do google, que da dicas onde melhorar https://developers.google.com/speed/pagespeed/insights/

**Comment by amedtler** [comment]
Esse item não vou ter condições de fazer, pois os ajustes vão demorar muito tempo (cerca de 10 dias) e quando começar a mexer nisso, precisa ir até o fim. Acho melhor deixar para o programador que estão contratando. 
Obs: esse item não estava dentro do orçamento.

**Comment by roelsmich** [comment]
ok
