### ISSUE TITLE
Carrinho - Incluir imagem das formas de pagamento

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#9]

**Comment by amedtler** [comment]
Como deve ficar o layout/disposição?

**Comment by arielrinnert** [comment]
![carrinho](https://cloud.githubusercontent.com/assets/19783148/16547835/e8ad64c2-4150-11e6-91d9-5cee015906e5.png)

já pode colocar tbm os selos de vantagens mercadológicas pfv..

**Comment by amedtler** [comment]
Implementado

**Comment by arielrinnert** [comment]
feito
