### ISSUE TITLE
order-received - Adicionar informações na tela do resumo da compra 

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#91]
Na planilha está assim: 
Na última página de compra, onde tem um resumo da compra, colocar passo-a-passo do pós venda (isso aqui eu vou criar o texto ou uma arte e passar te passar pra colocar) e botão escrito "Enviar resumo da compra para meu e-mail e retornar a página principal"

Estou no aguardo...

**Comment by arielrinnert** [comment]
Isso ai mesmo, o negócio é aparecer abaixo do resumo de compra que já aparece lá, um texto e uma imagem esticada (que vai ser criada).. por hora da pra lançar só o texto em destaque (negrito de repente..) e ai quando a imagem ficar pronta eu peço pra Mar já montar uma caixa com texto e imagem junto..

Texto: "Sua compra foi efetuada com sucesso! Assim que seu pagamento for confirmado, nossa equipe preparará o seu pedido, encaminhará para o correio e manterá você sempre a par do status da entrega. Enviaremos a você por e-mail o resumo com as informações da compra, a nota fiscal do(s) produto(s) adquirido(s), o código de rastreio e uma pesquisa de satisfação para saber como foi a sua experiência! 

A Ocean Drop agradece a preferência e confiança em nossos produtos!

Tenha um bom dia!"

**Comment by amedtler** [comment]
Destacar a fonte.

**Comment by amedtler** [comment]
Item 9 da planilha

**Comment by arielrinnert** [comment]
@roelsmich solicitar arte final pra @margpm

**Comment by roelsmich** [comment]
@margpm por gentiliza passar a arte para  Andreson

**Comment by margpm** [comment]
Envio imagem da arte, e icones.

**Comment by margpm** [comment]
![arte_finalizacao_compra5](https://cloud.githubusercontent.com/assets/23121158/20325648/bbbe64a8-ab6c-11e6-8bab-f14b897e9769.jpg)

**Comment by margpm** [comment]
Referencias das cores:
#82d2eb
#00afe6
#003255
#001e9b

**Comment by margpm** [comment]
A cor do texto, será a mesma que a cor dos icones, #333536 fonte open sans

**Comment by margpm** [comment]
![icon_1](https://cloud.githubusercontent.com/assets/23121158/20326104/77d2b1de-ab6e-11e6-9d1b-fb8407bbaed4.png)
![icon_2](https://cloud.githubusercontent.com/assets/23121158/20326101/77d0635c-ab6e-11e6-9bf1-22aeb0fb2b5d.png)
![icon_3](https://cloud.githubusercontent.com/assets/23121158/20326102/77d11356-ab6e-11e6-96ad-346e9681c583.png)
![icon_4](https://cloud.githubusercontent.com/assets/23121158/20326103/77d1c9e0-ab6e-11e6-8fbf-a147ff2a4fc5.png)

**Comment by margpm** [comment]
![1](https://cloud.githubusercontent.com/assets/23121158/20326270/2ac665e2-ab6f-11e6-92e1-c3000adb55b6.png)
![2](https://cloud.githubusercontent.com/assets/23121158/20326271/2ac80dca-ab6f-11e6-8620-38fb47df0b30.png)
![3](https://cloud.githubusercontent.com/assets/23121158/20326272/2af35430-ab6f-11e6-8022-799c2f67c6dd.png)
![4](https://cloud.githubusercontent.com/assets/23121158/20326273/2af3f8ea-ab6f-11e6-9d69-101f65e8ec59.png)

**Comment by margpm** [comment]
Se estiver faltando algo, por favor avisa o quanto antes @amedtler

**Comment by amedtler** [comment]
Implementado. 
Se estiver logado, pode utilizar esse link para verificar. 
https://oceandrop.com.br/checkout/order-received/2569/?key=wc_order_58323083c6498 

Obs: Como os textos tem tamanhos diferentes, não tem como deixar as caixas sempre com o mesmo tamanho.

**Comment by roelsmich** [comment]
Verifiquei no link é não tem caixas e o cliente pode ficar confuso.  Por gentileza inclua da forma que mar fez (numeros nos circulos coloridos, os icones na mesma altura...). O tamanho do texto pode ser diferente, deixa margem branco abaixo dos paragrafos para que as caixas ficam do mesmo tamanho.  @amedtler

**Comment by amedtler** [comment]
Deve estar com cache. Atualiza a página algumas vezes ou abre em uma janela anônima. Command + R

**Comment by roelsmich** [comment]
verdade
