### ISSUE TITLE
Integrar Woocommerce com o ContaAzul

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#92]
Analisando

**Comment by amedtler** [comment]
Cara, não encontrei muita coisa, no site deles também não. Por acaso tem algum email de contato? Se tiver,  poderia mandar um email com cópia para mim, explicando o que pretende fazer. Dessa forma facilitaria bastante.

**Comment by arielrinnert** [comment]
vou fazer isso sim! já coloco aqui os objetivos pra ti:
- após uma compra/pagamento, criar cadastro do cliente no Conta Azul (não repetir cadastros de usuários do mesmo e-mail)
- após o cadastro do cliente, cadastrar a venda no Conta Azul;

a partir desta etapa, eu vou consultar com o ContaAzul, se a geração automática da NF a partir da venda tem alguma ligação com o Woocommerce ou não, mas acho que não..

**Comment by amedtler** [comment]
É possível exportar. Instalei um plugin onde tu mesmo pode fazer isso. 
Na área de usuários, clica na opção export user data. 
Vai aparecer uma lista com vários campos. Vai clicando nos campos que deseja exportar (eles vão aparecer na coluna da direita), depois escolhe o formato (excel ou csv), coloca um nome qualquer. 
Ah! Clica também em advanced options show e seleciona a opção customer em role.

**Comment by arielrinnert** [comment]
Wooooooooooooow!!!

Sensacional, salvou kkkkkk!

Boa ta bom assim, o Conta Azul não integra porcaria nenhuma mesmo, já to lá brigando com eles por causa disso.. hahahah..

valeu!

**Comment by wesleycampos** [comment]
Alguém conseguiu fazer essa interação no Woocommerce e conta Azul?

- Após uma compra/pagamento, criar cadastro do cliente no Conta Azul (não repetir cadastros de usuários do mesmo e-mail)

- Após o cadastro do cliente, cadastrar a venda no Conta Azul;

**Comment by fredericoo** [comment]
> Alguém conseguiu fazer essa interação no Woocommerce e conta Azul?
> 
> * Após uma compra/pagamento, criar cadastro do cliente no Conta Azul (não repetir cadastros de usuários do mesmo e-mail)
> * Após o cadastro do cliente, cadastrar a venda no Conta Azul;

Criei um plugin pra isso semana passada: https://github.com/fredericoo/woocommerce-contaazul

Aceito pull requests de melhorias!

**Comment by lucassandes4** [comment]
Estou precisando desse plugin! Como posso utilizar? Pode me passar os passos?

**Comment by lucassandes4** [comment]
> > Alguém conseguiu fazer essa interação no Woocommerce e conta Azul?
> > 
> > * Após uma compra/pagamento, criar cadastro do cliente no Conta Azul (não repetir cadastros de usuários do mesmo e-mail)
> > * Após o cadastro do cliente, cadastrar a venda no Conta Azul;
> 
> Criei um plugin pra isso semana passada: https://github.com/fredericoo/woocommerce-contaazul
> 
> Aceito pull requests de melhorias!

Estou precisando desse plugin! Como posso utilizar? Pode me passar os passos?
