### ISSUE TITLE
Integrar Woocommerce com o Correio

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#93]
Analisando

**Comment by amedtler** [comment]
Número do contrato: 9912393595
Código ADM: 16079604
SERVIÇOS CONTRATADOS:

SEDEX 40096
PAC 41068
Contato: tatianebrasil@correios.com.br

**Comment by amedtler** [comment]
Enviado email para o suporte.

**Comment by arielrinnert** [comment]
Código adm: 16079604
Senha adm: xdpyfa

**Comment by arielrinnert** [comment]
Vou te passar aqui os objetivos da integração:
- gerar e apresentar automaticamente o preço e prazo estimado para a entrega dos produtos, tanto na página do carrinho quanto do checkout quando o cliente informa o CEP;
- após o pagamento, gerar automaticamente a venda no Sigep;
- após o envio (o Sigep atualiza automaticamente o sistema com o código de rastreio), atualizar área do cliente com dados do rastreio, continuamente (conforme o produto vai mudando de lugar durante o envio)

**Comment by amedtler** [comment]
Ok. Já está gerando os valores e prazo de acordo com o CEP. 
Estou vendo essa questão do sigep, não tenho certeza absoluta se isso já funciona automaticamente, acredito que não. Assim que tiver uma confirmação, volto aqui.

**Comment by arielrinnert** [comment]
certo eu vi lá! dai é só ativar a funcionalidade de indicar o prazo.. nesse caso, pode tirar aquela estimativa média geral q colocamos pra apresentar.. e ai, pra esse texto novo, só coloca a palavra "estimado" no meio do prazo pro cliente não encher o saco depois.

**Comment by amedtler** [comment]
Não consegui colocar a palavra dentro do mesmo texto padrão do plugin, falei até com o criador do plugin que me recomendou algumas opções mas não deu certo, então até que ele responda, deixei no mesmo padrão que estava antes (prazo de 10 dias..., porém troquei para prazo estimado)

**Comment by arielrinnert** [comment]
ta saquei, então faz assim, pode deixar no variável por hora, mesmo q não tenha a palavra "estimado".. se alguém responder agente volta pra esse padrão... se no meio tempo o desenvolvedor solucionar ai colocamos certo lá..

**Comment by amedtler** [comment]
Buenas, deixei o padrão do plugin.

**Comment by arielrinnert** [comment]
ta fico no aguardo então de novidades...

**Comment by arielrinnert** [comment]
dai brow, alguma novidade quanto a esta integração? abraço..

**Comment by amedtler** [comment]
Falar novamente com o desenvolvedor do plugin.

**Comment by arielrinnert** [comment]
cara vamos encerrar esse aqui pois adquirimos um sistema que agiliza isso já.. fica aberto só a diferença entre o valor do frete computado no site e cobrado no correio..
