### ISSUE TITLE
Incluir chat ZOPIN

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#94]
Tem como integrar, porém 14 dias grátis. Depois disso precisa pagar. 
Dá uma olhada nos planos https://pt.zopim.com/pricing/ 
Vamos integrar pra ver como funciona?

**Comment by arielrinnert** [comment]
cara é sóo pra 14 dias grátis ou ele registra o histórico por 14 dias só? pq se for free geral e só armazenar por 14 dias não da nada, podemos implementar.. se for pra pagar da uma segurada q vou ver um outro serviço antes..

**Comment by amedtler** [comment]
Pelo que eu entendi é livre, só o histórico que armazena por 14 dias. Acho que é melhor tu criar a conta e me passar o acesso. Plano LITE.

**Comment by arielrinnert** [comment]
cara assim, falei com o pessoal do atendimento aqui, e eles pediram pra atrasar até o final do mês a implementação dessa ferramenta pra eles se prepararem melhor ok?

**Comment by arielrinnert** [comment]
@roelsmich essa atividade depende da centralização da comunicação (ex. zendesk)

**Comment by roelsmich** [comment]
Sugestão da ariel =>

 minha sugestão pra implementar o Zopin:

## \- eu não avancei nisso ainda pq acredito q se não for feita uma gestão bem feita não tem nem pq implementar (ok podemos testar mas me parece claro q vai surgir demanda dai..)

@roelsmich minha sugestão pra implementar o Zopin:
- eu não avancei nisso ainda pq acredito q se não for feita uma gestão bem feita não tem nem pq implementar (ok podemos testar mas me parece claro q vai surgir demanda dai..)
- a solução q vejo pra isso é centralizar o atendimento ao cliente numa plataforma única, q hoje vejo o Zendesk como ideal pra isso (apesar de não conhecer muito bem ele, e menos ainda outras soluções do mercado)
- eu já falei diversas vezes pro Lucas e dps pra Ju se agilizarem com isso mas até agora nada (eles tem coisa q chega já pra fazer e tão postergando..)
- logo: passa pra Ju um deadline pra ferramenta ser implementada e cadastra direto as contas dela no Zopin (falecom@ e juliana@).. assim ela vai receber as demandas de qualquer modo, organizada ou não, mas dai vai ser problema dela se preparar pra isso..

**Comment by roelsmich** [comment]
segue o codigo 


<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="https://v2.zopim.com/?4O42vLc8KxltGObO5fnBeNsjLDK5CtyX";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>

**Comment by amedtler** [comment]
Vou fazer a integração via plugin, pois nesse caso vocês podem desativar o plugin caso tenha algum problema. Porém, preciso das seguintes informações: 

Zendesk Chat Username (E-mail): 
Zendesk Chat Password:

**Comment by roelsmich** [comment]
boa, 

email : falecom@oceandrop.com.br
password : spirulinaechlorella

**Comment by amedtler** [comment]
Já está ativo.

**Comment by roelsmich** [comment]
ja tamos testando hehe
