### ISSUE TITLE
Carrinho - Adicionar botões extras para compra de porta cápsula

### ISSUE THREAD

**Issue by amedtler** [amedtler/oceandrop#96]

**Comment by arielrinnert** [comment]
Cara nessa atividade, a ideia é colocar dois botões (um pra cada porta capsulas) abaixo da tabela de resumo do pedido (antes da tabela de total do carrinho e frete), sendo que só devem aparecer quando tiver algum produto no carrinho..

Podem ser dois botões azuis já que o botão de finalizar a compra é verde..  pode ser retangular, ficar um ao lado do outro e ocupar quase toda a largura da tabela..

**Comment by arielrinnert** [comment]
a funcionalidade é pra ser a mesma dos botões de "adicionar ao carrinho" da home page

**Comment by amedtler** [comment]
Adicionar case spirulina...

**Comment by arielrinnert** [comment]
essa atividade aqui já está listada anteriormente.. precisa ser feito ainda..
